package com.homtrip.model;

import java.util.Arrays;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

import com.homtrip.utils.DateUtils;
import com.homtrip.utils.NumberUtils;

public class HotelOrderVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.instanceGuid
     *
     * @mbggenerated
     */
    private Integer instanceguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.gzlzt
     *状态，工作流状态
     * @mbggenerated
     */
    private String gzlzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.lcjssj
     *
     * @mbggenerated
     */
    private Date lcjssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sqbm
     *
     * @mbggenerated
     */
    private String sqbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sqbmguid
     *
     * @mbggenerated
     */
    private String sqbmguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sqr
     *
     * @mbggenerated
     */
    private String sqr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sqrguid
     *
     * @mbggenerated
     */
    private String sqrguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sqsj
     *
     * @mbggenerated
     */
    private Date sqsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sqdh
     *订单号，申请单号
     * @mbggenerated
     */
    private String sqdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ptdh
     *
     * @mbggenerated
     */
    private String ptdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ddsx
     *订单来源
     * @mbggenerated
     */
    private String ddsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.rzrq
     *入住日期
     * @mbggenerated
     */
    @DateTimeFormat(iso=ISO.DATE) 
    private Date rzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.tfrq
     *
     * @mbggenerated
     */
    private Date tfrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.rzts
     *入住天数
     * @mbggenerated
     */
    private Integer rzts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.zje
     *
     * @mbggenerated
     */
    private Double zje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.kpzt
     *
     * @mbggenerated
     */
    private String kpzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yszt
     *
     * @mbggenerated
     */
    private String yszt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.houseGuid
     *
     * @mbggenerated
     */
    private String houseguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.xfdh
     *
     * @mbggenerated
     */
    private String xfdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ddzt
     *订单状态
     * @mbggenerated
     */
    private String ddzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qlzt
     *
     * @mbggenerated
     */
    private String qlzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.cwskzt
     *财务收款状态
     * @mbggenerated
     */
    private String cwskzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ffyj
     *
     * @mbggenerated
     */
    private Double ffyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.jff
     *
     * @mbggenerated
     */
    private Double jff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.jg
     *
     * @mbggenerated
     */
    private Double jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.djzk
     *
     * @mbggenerated
     */
    private Double djzk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.tszk
     *
     * @mbggenerated
     */
    private Double tszk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ffxj
     *
     * @mbggenerated
     */
    private Double ffxj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.zkje
     *
     * @mbggenerated
     */
    private Double zkje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sjfj
     *
     * @mbggenerated
     */
    private Double sjfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qllrr
     *
     * @mbggenerated
     */
    private String qllrr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qlsj
     *
     * @mbggenerated
     */
    private Date qlsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qlr
     *
     * @mbggenerated
     */
    private String qlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qlrguid
     *
     * @mbggenerated
     */
    private String qlrguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qlbz
     *
     * @mbggenerated
     */
    private String qlbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qljszt
     *
     * @mbggenerated
     */
    private String qljszt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qtfy
     *
     * @mbggenerated
     */
    private Double qtfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ysk
     *
     * @mbggenerated
     */
    private Double ysk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yj
     *
     * @mbggenerated
     */
    private Double yj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yk
     *
     * @mbggenerated
     */
    private Double yk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ttmc
     *
     * @mbggenerated
     */
    private String ttmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.xm
     *入住人姓名，姓名
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.lxdh
     *手机，联系电话
     * @mbggenerated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sfz
     *
     * @mbggenerated
     */
    private String sfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.krly
     *
     * @mbggenerated
     */
    private String krly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.rzsj
     *
     * @mbggenerated
     */
    private Date rzsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.tfsj
     *
     * @mbggenerated
     */
    private Date tfsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.laifou
     *
     * @mbggenerated
     */
    private String laifou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.zdqxsj_xs
     *
     * @mbggenerated
     */
    private String zdqxsjXs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.zdqxsj_fz
     *
     * @mbggenerated
     */
    private String zdqxsjFz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.noshow
     *
     * @mbggenerated
     */
    private String noshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.noshowzrr
     *
     * @mbggenerated
     */
    private String noshowzrr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.noshowqrsj
     *
     * @mbggenerated
     */
    private Date noshowqrsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.noshowbz
     *
     * @mbggenerated
     */
    private String noshowbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.qxbz
     *
     * @mbggenerated
     */
    private String qxbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yzGuid
     *
     * @mbggenerated
     */
    private String yzguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ptxxGuid
     *
     * @mbggenerated
     */
    private String ptxxguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yjl
     *
     * @mbggenerated
     */
    private Double yjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.hxyl
     *
     * @mbggenerated
     */
    private Double hxyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ywtcxs
     *
     * @mbggenerated
     */
    private Double ywtcxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sfdc
     *
     * @mbggenerated
     */
    private String sfdc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.sfycfj
     *
     * @mbggenerated
     */
    private String sfycfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.noshowcldh
     *
     * @mbggenerated
     */
    private String noshowcldh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.noshowclsj
     *
     * @mbggenerated
     */
    private Date noshowclsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.noshowclbz
     *
     * @mbggenerated
     */
    private String noshowclbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.zcqx
     *
     * @mbggenerated
     */
    private String zcqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yhje
     *
     * @mbggenerated
     */
    private Double yhje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yhsqr
     *
     * @mbggenerated
     */
    private String yhsqr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.yhsm
     *
     * @mbggenerated
     */
    private String yhsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.itemid
     *
     * @mbggenerated
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ddskzt
     *
     * @mbggenerated
     */
    private String ddskzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ywy
     *
     * @mbggenerated
     */
    private String ywy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.ywyid
     *
     * @mbggenerated
     */
    private String ywyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.rzsjqj
     *
     * @mbggenerated
     */
    private String rzsjqj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.fj_ext
     *
     * @mbggenerated
     */
    private String fjExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb.fj
     *
     * @mbggenerated
     */
    private byte[] fj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.guid
     *
     * @return the value of fwddzb.guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.guid
     *
     * @param guid the value for fwddzb.guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.instanceGuid
     *
     * @return the value of fwddzb.instanceGuid
     *
     * @mbggenerated
     */
    public Integer getInstanceguid() {
        return instanceguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.instanceGuid
     *
     * @param instanceguid the value for fwddzb.instanceGuid
     *
     * @mbggenerated
     */
    public void setInstanceguid(Integer instanceguid) {
        this.instanceguid = instanceguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.gzlzt
     *
     * @return the value of fwddzb.gzlzt
     *
     * @mbggenerated
     */
    public String getGzlzt() {
        return gzlzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.gzlzt
     *
     * @param gzlzt the value for fwddzb.gzlzt
     *
     * @mbggenerated
     */
    public void setGzlzt(String gzlzt) {
        this.gzlzt = gzlzt == null ? null : gzlzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.lcjssj
     *
     * @return the value of fwddzb.lcjssj
     *
     * @mbggenerated
     */
    public Date getLcjssj() {
        return lcjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.lcjssj
     *
     * @param lcjssj the value for fwddzb.lcjssj
     *
     * @mbggenerated
     */
    public void setLcjssj(Date lcjssj) {
        this.lcjssj = lcjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sqbm
     *
     * @return the value of fwddzb.sqbm
     *
     * @mbggenerated
     */
    public String getSqbm() {
        return sqbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sqbm
     *
     * @param sqbm the value for fwddzb.sqbm
     *
     * @mbggenerated
     */
    public void setSqbm(String sqbm) {
        this.sqbm = sqbm == null ? null : sqbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sqbmguid
     *
     * @return the value of fwddzb.sqbmguid
     *
     * @mbggenerated
     */
    public String getSqbmguid() {
        return sqbmguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sqbmguid
     *
     * @param sqbmguid the value for fwddzb.sqbmguid
     *
     * @mbggenerated
     */
    public void setSqbmguid(String sqbmguid) {
        this.sqbmguid = sqbmguid == null ? null : sqbmguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sqr
     *
     * @return the value of fwddzb.sqr
     *
     * @mbggenerated
     */
    public String getSqr() {
        return sqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sqr
     *
     * @param sqr the value for fwddzb.sqr
     *
     * @mbggenerated
     */
    public void setSqr(String sqr) {
        this.sqr = sqr == null ? null : sqr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sqrguid
     *
     * @return the value of fwddzb.sqrguid
     *
     * @mbggenerated
     */
    public String getSqrguid() {
        return sqrguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sqrguid
     *
     * @param sqrguid the value for fwddzb.sqrguid
     *
     * @mbggenerated
     */
    public void setSqrguid(String sqrguid) {
        this.sqrguid = sqrguid == null ? null : sqrguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sqsj
     *
     * @return the value of fwddzb.sqsj
     *
     * @mbggenerated
     */
    public Date getSqsj() {
        return sqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sqsj
     *
     * @param sqsj the value for fwddzb.sqsj
     *
     * @mbggenerated
     */
    public void setSqsj(Date sqsj) {
        this.sqsj = sqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sqdh
     *
     * @return the value of fwddzb.sqdh
     *
     * @mbggenerated
     */
    public String getSqdh() {
        return sqdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sqdh
     *
     * @param sqdh the value for fwddzb.sqdh
     *
     * @mbggenerated
     */
    public void setSqdh(String sqdh) {
        this.sqdh = sqdh == null ? null : sqdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ptdh
     *
     * @return the value of fwddzb.ptdh
     *
     * @mbggenerated
     */
    public String getPtdh() {
        return ptdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ptdh
     *
     * @param ptdh the value for fwddzb.ptdh
     *
     * @mbggenerated
     */
    public void setPtdh(String ptdh) {
        this.ptdh = ptdh == null ? null : ptdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ddsx
     *
     * @return the value of fwddzb.ddsx
     *
     * @mbggenerated
     */
    public String getDdsx() {
        return ddsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ddsx
     *
     * @param ddsx the value for fwddzb.ddsx
     *
     * @mbggenerated
     */
    public void setDdsx(String ddsx) {
        this.ddsx = ddsx == null ? null : ddsx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.rzrq
     *
     * @return the value of fwddzb.rzrq
     *
     * @mbggenerated
     */
    public Date getRzrq() {
        return rzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.rzrq
     *
     * @param rzrq the value for fwddzb.rzrq
     *
     * @mbggenerated
     */
    public void setRzrq(Date rzrq) {
        this.rzrq = rzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.tfrq
     *
     * @return the value of fwddzb.tfrq
     *
     * @mbggenerated
     */
    public Date getTfrq() {
        return tfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.tfrq
     *
     * @param tfrq the value for fwddzb.tfrq
     *
     * @mbggenerated
     */
    public void setTfrq(Date tfrq) {
        this.tfrq = tfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.rzts
     *
     * @return the value of fwddzb.rzts
     *
     * @mbggenerated
     */
    public Integer getRzts() {
        return rzts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.rzts
     *
     * @param rzts the value for fwddzb.rzts
     *
     * @mbggenerated
     */
    public void setRzts(Integer rzts) {
        this.rzts = rzts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.zje
     *
     * @return the value of fwddzb.zje
     *
     * @mbggenerated
     */
    public Double getZje() {
        return zje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.zje
     *
     * @param zje the value for fwddzb.zje
     *
     * @mbggenerated
     */
    public void setZje(Double zje) {
        this.zje = zje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.kpzt
     *
     * @return the value of fwddzb.kpzt
     *
     * @mbggenerated
     */
    public String getKpzt() {
        return kpzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.kpzt
     *
     * @param kpzt the value for fwddzb.kpzt
     *
     * @mbggenerated
     */
    public void setKpzt(String kpzt) {
        this.kpzt = kpzt == null ? null : kpzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yszt
     *
     * @return the value of fwddzb.yszt
     *
     * @mbggenerated
     */
    public String getYszt() {
        return yszt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yszt
     *
     * @param yszt the value for fwddzb.yszt
     *
     * @mbggenerated
     */
    public void setYszt(String yszt) {
        this.yszt = yszt == null ? null : yszt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.houseGuid
     *
     * @return the value of fwddzb.houseGuid
     *
     * @mbggenerated
     */
    public String getHouseguid() {
        return houseguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.houseGuid
     *
     * @param houseguid the value for fwddzb.houseGuid
     *
     * @mbggenerated
     */
    public void setHouseguid(String houseguid) {
        this.houseguid = houseguid == null ? null : houseguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.xfdh
     *
     * @return the value of fwddzb.xfdh
     *
     * @mbggenerated
     */
    public String getXfdh() {
        return xfdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.xfdh
     *
     * @param xfdh the value for fwddzb.xfdh
     *
     * @mbggenerated
     */
    public void setXfdh(String xfdh) {
        this.xfdh = xfdh == null ? null : xfdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ddzt
     *
     * @return the value of fwddzb.ddzt
     *
     * @mbggenerated
     */
    public String getDdzt() {
        return ddzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ddzt
     *
     * @param ddzt the value for fwddzb.ddzt
     *
     * @mbggenerated
     */
    public void setDdzt(String ddzt) {
        this.ddzt = ddzt == null ? null : ddzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qlzt
     *
     * @return the value of fwddzb.qlzt
     *
     * @mbggenerated
     */
    public String getQlzt() {
        return qlzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qlzt
     *
     * @param qlzt the value for fwddzb.qlzt
     *
     * @mbggenerated
     */
    public void setQlzt(String qlzt) {
        this.qlzt = qlzt == null ? null : qlzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.cwskzt
     *
     * @return the value of fwddzb.cwskzt
     *
     * @mbggenerated
     */
    public String getCwskzt() {
        return cwskzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.cwskzt
     *
     * @param cwskzt the value for fwddzb.cwskzt
     *
     * @mbggenerated
     */
    public void setCwskzt(String cwskzt) {
        this.cwskzt = cwskzt == null ? null : cwskzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ffyj
     *房费原价
     * @return the value of fwddzb.ffyj
     *
     * @mbggenerated
     */
    public Double getFfyj() {
        return ffyj==null?0:ffyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ffyj
     *
     * @param ffyj the value for fwddzb.ffyj
     *
     * @mbggenerated
     */
    public void setFfyj(Double ffyj) {
        this.ffyj = ffyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.jff
     *
     * @return the value of fwddzb.jff
     *
     * @mbggenerated
     */
    public Double getJff() {
        return jff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.jff
     *
     * @param jff the value for fwddzb.jff
     *
     * @mbggenerated
     */
    public void setJff(Double jff) {
        this.jff = jff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.jg
     *
     * @return the value of fwddzb.jg
     *
     * @mbggenerated
     */
    public Double getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.jg
     *
     * @param jg the value for fwddzb.jg
     *
     * @mbggenerated
     */
    public void setJg(Double jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.djzk
     *
     * @return the value of fwddzb.djzk
     *
     * @mbggenerated
     */
    public Double getDjzk() {
        return djzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.djzk
     *
     * @param djzk the value for fwddzb.djzk
     *
     * @mbggenerated
     */
    public void setDjzk(Double djzk) {
        this.djzk = djzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.tszk
     *
     * @return the value of fwddzb.tszk
     *
     * @mbggenerated
     */
    public Double getTszk() {
        return tszk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.tszk
     *
     * @param tszk the value for fwddzb.tszk
     *
     * @mbggenerated
     */
    public void setTszk(Double tszk) {
        this.tszk = tszk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ffxj
     *
     * @return the value of fwddzb.ffxj
     *
     * @mbggenerated
     */
    public Double getFfxj() {
        return ffxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ffxj
     *
     * @param ffxj the value for fwddzb.ffxj
     *
     * @mbggenerated
     */
    public void setFfxj(Double ffxj) {
        this.ffxj = ffxj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.zkje
     *
     * @return the value of fwddzb.zkje
     *
     * @mbggenerated
     */
    public Double getZkje() {
        return zkje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.zkje
     *
     * @param zkje the value for fwddzb.zkje
     *
     * @mbggenerated
     */
    public void setZkje(Double zkje) {
        this.zkje = zkje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sjfj
     *
     * @return the value of fwddzb.sjfj
     *
     * @mbggenerated
     */
    public Double getSjfj() {
        return sjfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sjfj
     *
     * @param sjfj the value for fwddzb.sjfj
     *
     * @mbggenerated
     */
    public void setSjfj(Double sjfj) {
        this.sjfj = sjfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qllrr
     *
     * @return the value of fwddzb.qllrr
     *
     * @mbggenerated
     */
    public String getQllrr() {
        return qllrr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qllrr
     *
     * @param qllrr the value for fwddzb.qllrr
     *
     * @mbggenerated
     */
    public void setQllrr(String qllrr) {
        this.qllrr = qllrr == null ? null : qllrr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qlsj
     *
     * @return the value of fwddzb.qlsj
     *
     * @mbggenerated
     */
    public Date getQlsj() {
        return qlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qlsj
     *
     * @param qlsj the value for fwddzb.qlsj
     *
     * @mbggenerated
     */
    public void setQlsj(Date qlsj) {
        this.qlsj = qlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qlr
     *
     * @return the value of fwddzb.qlr
     *
     * @mbggenerated
     */
    public String getQlr() {
        return qlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qlr
     *
     * @param qlr the value for fwddzb.qlr
     *
     * @mbggenerated
     */
    public void setQlr(String qlr) {
        this.qlr = qlr == null ? null : qlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qlrguid
     *
     * @return the value of fwddzb.qlrguid
     *
     * @mbggenerated
     */
    public String getQlrguid() {
        return qlrguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qlrguid
     *
     * @param qlrguid the value for fwddzb.qlrguid
     *
     * @mbggenerated
     */
    public void setQlrguid(String qlrguid) {
        this.qlrguid = qlrguid == null ? null : qlrguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qlbz
     *
     * @return the value of fwddzb.qlbz
     *
     * @mbggenerated
     */
    public String getQlbz() {
        return qlbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qlbz
     *
     * @param qlbz the value for fwddzb.qlbz
     *
     * @mbggenerated
     */
    public void setQlbz(String qlbz) {
        this.qlbz = qlbz == null ? null : qlbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qljszt
     *
     * @return the value of fwddzb.qljszt
     *
     * @mbggenerated
     */
    public String getQljszt() {
        return qljszt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qljszt
     *
     * @param qljszt the value for fwddzb.qljszt
     *
     * @mbggenerated
     */
    public void setQljszt(String qljszt) {
        this.qljszt = qljszt == null ? null : qljszt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qtfy
     *
     * @return the value of fwddzb.qtfy
     *
     * @mbggenerated
     */
    public Double getQtfy() {
        return qtfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qtfy
     *
     * @param qtfy the value for fwddzb.qtfy
     *
     * @mbggenerated
     */
    public void setQtfy(Double qtfy) {
        this.qtfy = qtfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ysk
     *
     * @return the value of fwddzb.ysk
     *
     * @mbggenerated
     */
    public Double getYsk() {
        return ysk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ysk
     *
     * @param ysk the value for fwddzb.ysk
     *
     * @mbggenerated
     */
    public void setYsk(Double ysk) {
        this.ysk = ysk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yj
     *
     * @return the value of fwddzb.yj
     *
     * @mbggenerated
     */
    public Double getYj() {
        return yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yj
     *
     * @param yj the value for fwddzb.yj
     *
     * @mbggenerated
     */
    public void setYj(Double yj) {
        this.yj = yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yk
     *
     * @return the value of fwddzb.yk
     *
     * @mbggenerated
     */
    public Double getYk() {
        return yk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yk
     *
     * @param yk the value for fwddzb.yk
     *
     * @mbggenerated
     */
    public void setYk(Double yk) {
        this.yk = yk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ttmc
     *
     * @return the value of fwddzb.ttmc
     *
     * @mbggenerated
     */
    public String getTtmc() {
        return ttmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ttmc
     *
     * @param ttmc the value for fwddzb.ttmc
     *
     * @mbggenerated
     */
    public void setTtmc(String ttmc) {
        this.ttmc = ttmc == null ? null : ttmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.xm
     *
     * @return the value of fwddzb.xm
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.xm
     *
     * @param xm the value for fwddzb.xm
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.lxdh
     *
     * @return the value of fwddzb.lxdh
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.lxdh
     *
     * @param lxdh the value for fwddzb.lxdh
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sfz
     *
     * @return the value of fwddzb.sfz
     *
     * @mbggenerated
     */
    public String getSfz() {
        return sfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sfz
     *
     * @param sfz the value for fwddzb.sfz
     *
     * @mbggenerated
     */
    public void setSfz(String sfz) {
        this.sfz = sfz == null ? null : sfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.krly
     *
     * @return the value of fwddzb.krly
     *
     * @mbggenerated
     */
    public String getKrly() {
        return krly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.krly
     *
     * @param krly the value for fwddzb.krly
     *
     * @mbggenerated
     */
    public void setKrly(String krly) {
        this.krly = krly == null ? null : krly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.bz
     *
     * @return the value of fwddzb.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.bz
     *
     * @param bz the value for fwddzb.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.rzsj
     *
     * @return the value of fwddzb.rzsj
     *
     * @mbggenerated
     */
    public Date getRzsj() {
        return rzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.rzsj
     *
     * @param rzsj the value for fwddzb.rzsj
     *
     * @mbggenerated
     */
    public void setRzsj(Date rzsj) {
        this.rzsj = rzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.tfsj
     *
     * @return the value of fwddzb.tfsj
     *
     * @mbggenerated
     */
    public Date getTfsj() {
        return tfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.tfsj
     *
     * @param tfsj the value for fwddzb.tfsj
     *
     * @mbggenerated
     */
    public void setTfsj(Date tfsj) {
        this.tfsj = tfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.laifou
     *
     * @return the value of fwddzb.laifou
     *
     * @mbggenerated
     */
    public String getLaifou() {
        return laifou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.laifou
     *
     * @param laifou the value for fwddzb.laifou
     *
     * @mbggenerated
     */
    public void setLaifou(String laifou) {
        this.laifou = laifou == null ? null : laifou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.zdqxsj_xs
     *
     * @return the value of fwddzb.zdqxsj_xs
     *
     * @mbggenerated
     */
    public String getZdqxsjXs() {
        return zdqxsjXs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.zdqxsj_xs
     *
     * @param zdqxsjXs the value for fwddzb.zdqxsj_xs
     *
     * @mbggenerated
     */
    public void setZdqxsjXs(String zdqxsjXs) {
        this.zdqxsjXs = zdqxsjXs == null ? null : zdqxsjXs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.zdqxsj_fz
     *
     * @return the value of fwddzb.zdqxsj_fz
     *
     * @mbggenerated
     */
    public String getZdqxsjFz() {
        return zdqxsjFz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.zdqxsj_fz
     *
     * @param zdqxsjFz the value for fwddzb.zdqxsj_fz
     *
     * @mbggenerated
     */
    public void setZdqxsjFz(String zdqxsjFz) {
        this.zdqxsjFz = zdqxsjFz == null ? null : zdqxsjFz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.noshow
     *
     * @return the value of fwddzb.noshow
     *
     * @mbggenerated
     */
    public String getNoshow() {
        return noshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.noshow
     *
     * @param noshow the value for fwddzb.noshow
     *
     * @mbggenerated
     */
    public void setNoshow(String noshow) {
        this.noshow = noshow == null ? null : noshow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.noshowzrr
     *
     * @return the value of fwddzb.noshowzrr
     *
     * @mbggenerated
     */
    public String getNoshowzrr() {
        return noshowzrr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.noshowzrr
     *
     * @param noshowzrr the value for fwddzb.noshowzrr
     *
     * @mbggenerated
     */
    public void setNoshowzrr(String noshowzrr) {
        this.noshowzrr = noshowzrr == null ? null : noshowzrr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.noshowqrsj
     *
     * @return the value of fwddzb.noshowqrsj
     *
     * @mbggenerated
     */
    public Date getNoshowqrsj() {
        return noshowqrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.noshowqrsj
     *
     * @param noshowqrsj the value for fwddzb.noshowqrsj
     *
     * @mbggenerated
     */
    public void setNoshowqrsj(Date noshowqrsj) {
        this.noshowqrsj = noshowqrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.noshowbz
     *
     * @return the value of fwddzb.noshowbz
     *
     * @mbggenerated
     */
    public String getNoshowbz() {
        return noshowbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.noshowbz
     *
     * @param noshowbz the value for fwddzb.noshowbz
     *
     * @mbggenerated
     */
    public void setNoshowbz(String noshowbz) {
        this.noshowbz = noshowbz == null ? null : noshowbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.qxbz
     *
     * @return the value of fwddzb.qxbz
     *
     * @mbggenerated
     */
    public String getQxbz() {
        return qxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.qxbz
     *
     * @param qxbz the value for fwddzb.qxbz
     *
     * @mbggenerated
     */
    public void setQxbz(String qxbz) {
        this.qxbz = qxbz == null ? null : qxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yzGuid
     *
     * @return the value of fwddzb.yzGuid
     *
     * @mbggenerated
     */
    public String getYzguid() {
        return yzguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yzGuid
     *
     * @param yzguid the value for fwddzb.yzGuid
     *
     * @mbggenerated
     */
    public void setYzguid(String yzguid) {
        this.yzguid = yzguid == null ? null : yzguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ptxxGuid
     *
     * @return the value of fwddzb.ptxxGuid
     *
     * @mbggenerated
     */
    public String getPtxxguid() {
        return ptxxguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ptxxGuid
     *
     * @param ptxxguid the value for fwddzb.ptxxGuid
     *
     * @mbggenerated
     */
    public void setPtxxguid(String ptxxguid) {
        this.ptxxguid = ptxxguid == null ? null : ptxxguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yjl
     *
     * @return the value of fwddzb.yjl
     *
     * @mbggenerated
     */
    public Double getYjl() {
        return yjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yjl
     *
     * @param yjl the value for fwddzb.yjl
     *
     * @mbggenerated
     */
    public void setYjl(Double yjl) {
        this.yjl = yjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.hxyl
     *
     * @return the value of fwddzb.hxyl
     *
     * @mbggenerated
     */
    public Double getHxyl() {
        return hxyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.hxyl
     *
     * @param hxyl the value for fwddzb.hxyl
     *
     * @mbggenerated
     */
    public void setHxyl(Double hxyl) {
        this.hxyl = hxyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ywtcxs
     *
     * @return the value of fwddzb.ywtcxs
     *
     * @mbggenerated
     */
    public Double getYwtcxs() {
        return ywtcxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ywtcxs
     *
     * @param ywtcxs the value for fwddzb.ywtcxs
     *
     * @mbggenerated
     */
    public void setYwtcxs(Double ywtcxs) {
        this.ywtcxs = ywtcxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sfdc
     *
     * @return the value of fwddzb.sfdc
     *
     * @mbggenerated
     */
    public String getSfdc() {
        return sfdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sfdc
     *
     * @param sfdc the value for fwddzb.sfdc
     *
     * @mbggenerated
     */
    public void setSfdc(String sfdc) {
        this.sfdc = sfdc == null ? null : sfdc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.sfycfj
     *
     * @return the value of fwddzb.sfycfj
     *
     * @mbggenerated
     */
    public String getSfycfj() {
        return sfycfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.sfycfj
     *
     * @param sfycfj the value for fwddzb.sfycfj
     *
     * @mbggenerated
     */
    public void setSfycfj(String sfycfj) {
        this.sfycfj = sfycfj == null ? null : sfycfj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.noshowcldh
     *
     * @return the value of fwddzb.noshowcldh
     *
     * @mbggenerated
     */
    public String getNoshowcldh() {
        return noshowcldh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.noshowcldh
     *
     * @param noshowcldh the value for fwddzb.noshowcldh
     *
     * @mbggenerated
     */
    public void setNoshowcldh(String noshowcldh) {
        this.noshowcldh = noshowcldh == null ? null : noshowcldh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.noshowclsj
     *
     * @return the value of fwddzb.noshowclsj
     *
     * @mbggenerated
     */
    public Date getNoshowclsj() {
        return noshowclsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.noshowclsj
     *
     * @param noshowclsj the value for fwddzb.noshowclsj
     *
     * @mbggenerated
     */
    public void setNoshowclsj(Date noshowclsj) {
        this.noshowclsj = noshowclsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.noshowclbz
     *
     * @return the value of fwddzb.noshowclbz
     *
     * @mbggenerated
     */
    public String getNoshowclbz() {
        return noshowclbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.noshowclbz
     *
     * @param noshowclbz the value for fwddzb.noshowclbz
     *
     * @mbggenerated
     */
    public void setNoshowclbz(String noshowclbz) {
        this.noshowclbz = noshowclbz == null ? null : noshowclbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.zcqx
     *
     * @return the value of fwddzb.zcqx
     *
     * @mbggenerated
     */
    public String getZcqx() {
        return zcqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.zcqx
     *
     * @param zcqx the value for fwddzb.zcqx
     *
     * @mbggenerated
     */
    public void setZcqx(String zcqx) {
        this.zcqx = zcqx == null ? null : zcqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yhje
     *
     * @return the value of fwddzb.yhje
     *
     * @mbggenerated
     */
    public Double getYhje() {
        return yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yhje
     *
     * @param yhje the value for fwddzb.yhje
     *
     * @mbggenerated
     */
    public void setYhje(Double yhje) {
        this.yhje = yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yhsqr
     *
     * @return the value of fwddzb.yhsqr
     *
     * @mbggenerated
     */
    public String getYhsqr() {
        return yhsqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yhsqr
     *
     * @param yhsqr the value for fwddzb.yhsqr
     *
     * @mbggenerated
     */
    public void setYhsqr(String yhsqr) {
        this.yhsqr = yhsqr == null ? null : yhsqr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.yhsm
     *
     * @return the value of fwddzb.yhsm
     *
     * @mbggenerated
     */
    public String getYhsm() {
        return yhsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.yhsm
     *
     * @param yhsm the value for fwddzb.yhsm
     *
     * @mbggenerated
     */
    public void setYhsm(String yhsm) {
        this.yhsm = yhsm == null ? null : yhsm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.itemid
     *
     * @return the value of fwddzb.itemid
     *
     * @mbggenerated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.itemid
     *
     * @param itemid the value for fwddzb.itemid
     *
     * @mbggenerated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.status
     *
     * @return the value of fwddzb.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.status
     *
     * @param status the value for fwddzb.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ddskzt
     *
     * @return the value of fwddzb.ddskzt
     *
     * @mbggenerated
     */
    public String getDdskzt() {
        return ddskzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ddskzt
     *
     * @param ddskzt the value for fwddzb.ddskzt
     *
     * @mbggenerated
     */
    public void setDdskzt(String ddskzt) {
        this.ddskzt = ddskzt == null ? null : ddskzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ywy
     *
     * @return the value of fwddzb.ywy
     *
     * @mbggenerated
     */
    public String getYwy() {
        return ywy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ywy
     *
     * @param ywy the value for fwddzb.ywy
     *
     * @mbggenerated
     */
    public void setYwy(String ywy) {
        this.ywy = ywy == null ? null : ywy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.ywyid
     *
     * @return the value of fwddzb.ywyid
     *
     * @mbggenerated
     */
    public String getYwyid() {
        return ywyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.ywyid
     *
     * @param ywyid the value for fwddzb.ywyid
     *
     * @mbggenerated
     */
    public void setYwyid(String ywyid) {
        this.ywyid = ywyid == null ? null : ywyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.rzsjqj
     *
     * @return the value of fwddzb.rzsjqj
     *
     * @mbggenerated
     */
    public String getRzsjqj() {
        return rzsjqj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.rzsjqj
     *
     * @param rzsjqj the value for fwddzb.rzsjqj
     *
     * @mbggenerated
     */
    public void setRzsjqj(String rzsjqj) {
        this.rzsjqj = rzsjqj == null ? null : rzsjqj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.fj_ext
     *
     * @return the value of fwddzb.fj_ext
     *
     * @mbggenerated
     */
    public String getFjExt() {
        return fjExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.fj_ext
     *
     * @param fjExt the value for fwddzb.fj_ext
     *
     * @mbggenerated
     */
    public void setFjExt(String fjExt) {
        this.fjExt = fjExt == null ? null : fjExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwddzb.fj
     *
     * @return the value of fwddzb.fj
     *
     * @mbggenerated
     */
    public byte[] getFj() {
        return fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwddzb.fj
     *
     * @param fj the value for fwddzb.fj
     *
     * @mbggenerated
     */
    public void setFj(byte[] fj) {
        this.fj = fj;
    }

	@Override
	public String toString() {
		return "HotelOrderVO [guid=" + guid + ", instanceguid=" + instanceguid + ", gzlzt=" + gzlzt + ", lcjssj="
				+ lcjssj + ", sqbm=" + sqbm + ", sqbmguid=" + sqbmguid + ", sqr=" + sqr + ", sqrguid=" + sqrguid
				+ ", sqsj=" + sqsj + ", sqdh=" + sqdh + ", ptdh=" + ptdh + ", ddsx=" + ddsx + ", rzrq=" + rzrq
				+ ", tfrq=" + tfrq + ", rzts=" + rzts + ", zje=" + zje + ", kpzt=" + kpzt + ", yszt=" + yszt
				+ ", houseguid=" + houseguid + ", xfdh=" + xfdh + ", ddzt=" + ddzt + ", qlzt=" + qlzt + ", cwskzt="
				+ cwskzt + ", ffyj=" + ffyj + ", jff=" + jff + ", jg=" + jg + ", djzk=" + djzk + ", tszk=" + tszk
				+ ", ffxj=" + ffxj + ", zkje=" + zkje + ", sjfj=" + sjfj + ", qllrr=" + qllrr + ", qlsj=" + qlsj
				+ ", qlr=" + qlr + ", qlrguid=" + qlrguid + ", qlbz=" + qlbz + ", qljszt=" + qljszt + ", qtfy=" + qtfy
				+ ", ysk=" + ysk + ", yj=" + yj + ", yk=" + yk + ", ttmc=" + ttmc + ", xm=" + xm + ", lxdh=" + lxdh
				+ ", sfz=" + sfz + ", krly=" + krly + ", bz=" + bz + ", rzsj=" + rzsj + ", tfsj=" + tfsj + ", laifou="
				+ laifou + ", zdqxsjXs=" + zdqxsjXs + ", zdqxsjFz=" + zdqxsjFz + ", noshow=" + noshow + ", noshowzrr="
				+ noshowzrr + ", noshowqrsj=" + noshowqrsj + ", noshowbz=" + noshowbz + ", qxbz=" + qxbz + ", yzguid="
				+ yzguid + ", ptxxguid=" + ptxxguid + ", yjl=" + yjl + ", hxyl=" + hxyl + ", ywtcxs=" + ywtcxs
				+ ", sfdc=" + sfdc + ", sfycfj=" + sfycfj + ", noshowcldh=" + noshowcldh + ", noshowclsj=" + noshowclsj
				+ ", noshowclbz=" + noshowclbz + ", zcqx=" + zcqx + ", yhje=" + yhje + ", yhsqr=" + yhsqr + ", yhsm="
				+ yhsm + ", itemid=" + itemid + ", status=" + status + ", ddskzt=" + ddskzt + ", ywy=" + ywy
				+ ", ywyid=" + ywyid + ", rzsjqj=" + rzsjqj + ", fjExt=" + fjExt + ", fj=" + Arrays.toString(fj) + "]";
	}
	
	public String getDdztText() {
		String d = getDdzt();
		return Status.getTextByKey(d);
	}
	
	
	public enum Status{
		//待处理 
		unhandle("0","待处理"),
//		未入住 
		uncheckin("1","未入住"),
//		已入住 
		checkin("2","已入住"),
//		已退房 
		checkout("3","已退房"),
//		已清理 
		cleanup("3.2","已清理"),
//		已完成 
		done("4","已完成"),
//		没出现 
		noShow("5","没出现"),
//		已暂停 
		pause("8","已暂停"),
//		已取消 
		cancel("9","已取消");
		private String key;
		
		private String text;

		private Status(String key,String text) {
			this.key = key;
			this.text = text;
		}

		public String getText() {
			return text;
		}

		public void setText(String text) {
			this.text = text;
		}

		public String getKey() {
			return key;
		}

		public void setKey(String key) {
			this.key = key;
		}
		
		public static String getTextByKey(String key) {
			Status[] ss = Status.values();
			for (int i = 0; i < ss.length; i++) {
				Status status = ss[i];
				if(status.getKey().equals(key)){
					return status.getText();
				}			
			}
			return "";
		}

		public static Status getByKey(String key) {
			Status[] ss = Status.values();
			for (int i = 0; i < ss.length; i++) {
				Status status = ss[i];
				if(status.getKey().equals(key)){
					return status;
				}			
			}
			return null;
		}

		
	}
	
	//扩展字段
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.ly
     *来源
     * @mbggenerated
     */
    private String ly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.kqzyh
     *快去住优惠
     * @mbggenerated
     */
    private Double kqzyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.xpze
     *选配总额
     * @mbggenerated
     */
    private Double xpze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.jdyh
     *酒店优惠
     * @mbggenerated
     */
    private Double jdyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.xszf
     *线上支付
     * @mbggenerated
     */
    private Double xszf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.fyjl
     *房佣金率
     * @mbggenerated
     */
    private Double fyjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.pyjl
     *配佣金率
     * @mbggenerated
     */
    private Double pyjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwddzb_ex.hysx
     *会员属性
     * @mbggenerated
     */
    private String hysx;

	public String getLy() {
		return ly;
	}

	public void setLy(String ly) {
		this.ly = ly;
	}

	public Double getKqzyh() {
		return kqzyh==null?0:kqzyh;
	}

	public void setKqzyh(Double kqzyh) {
		this.kqzyh = kqzyh;
	}

	public Double getXpze() {
		return xpze==null?0:xpze;
	}

	public void setXpze(Double xpze) {
		this.xpze = xpze;
	}
	/**
	 * 酒店优惠
	 * @return
	 */
	public Double getJdyh() {
		return jdyh==null?0:jdyh;
	}

	public void setJdyh(Double jdyh) {
		this.jdyh = jdyh;
	}


	public Double getXszf() {
		return xszf==null?0:xszf;
	}

	public void setXszf(Double xszf) {
		this.xszf = xszf;
	}

	public Double getFyjl() {
		return fyjl==null?0:fyjl;
	}

	public void setFyjl(Double fyjl) {
		this.fyjl = fyjl;
	}

	public Double getPyjl() {
		return pyjl==null?0:pyjl;
	}

	public void setPyjl(Double pyjl) {
		this.pyjl = pyjl;
	}

	public String getHysx() {
		return hysx;
	}

	public void setHysx(String hysx) {
		this.hysx = hysx;
	}
    
	
	public String getFfyjFormat() {
		return NumberUtils.formatCurrency(getFfyj());
	}
	
	public String getKqzyhFormat() {
		return NumberUtils.formatCurrency(getKqzyh());
	}
	
	public String getFfzeFormat() {
		return NumberUtils.formatCurrency(getFfyj()-getKqzyh());
	}
	
	
	public String getXpzeFormat() {
		return NumberUtils.formatCurrency(getXpze());
	}
	
	public String getJdyhFormat() {
		return NumberUtils.formatPercent(getJdyh());
	}
	
	public String getYhje2Format() {
		return NumberUtils.formatCurrency(getYhje2());
	}

	/**
	 * 酒店的优惠金额
	 * @return
	 */
	private double getYhje2() {
		return getJdyh()*getFfyj();
	}
	
	
	public String getDdjeFormat() {
		return NumberUtils.formatCurrency(getDdje());
	}

	private double getDdje() {
		return getFfyj()-getKqzyh()+getXpze()-getYhje2();
	}
	
	public String getXszfFormat() {
		return NumberUtils.formatPercent(getXszf());
	}
	
	
	public String getXfjeFormat() {
		return NumberUtils.formatCurrency(getXfje());
	}

	/**
	 * 线付金额
	 * @return
	 */
	private double getXfje() {
		return getDdje()*getXszf();
	}
	
	public String getFyjlFormat() {
		return NumberUtils.formatPercent(getFyjl());
	}
	
	
	public String getFfyj2Format() {
		return NumberUtils.formatCurrency(getFfyj2());
	}
	/**
	 * 房费佣金
	 * @return
	 */
	private double getFfyj2() {
		return getDdje()*getFyjl();
	}
	
	
	public String getPyjlFormat() {
		return NumberUtils.formatPercent(getPyjl());
	}
	
	
	public String getXpyjFormat() {
		return NumberUtils.formatCurrency(getXpyj());
	}

	/**
	 * 选配佣金
	 * @return
	 */
	private double getXpyj() {
		return getXpze()*getPyjl();
	}
	/**
	 * 线上收款
	 * @return
	 */
	public String getJdsyFormat() {
		return NumberUtils.formatCurrency(getJdsy());
	}

	/**
	 * 线上收款
	 * @return
	 */
	private double getJdsy() {
		return getXfje()-getFfyj2()-getXpyj()+getKqzyh();
	}
	
	
	public String getJdfxFormat() {
		return NumberUtils.formatCurrency(getDdje()-getXfje());
	}
	/**
	 * 总佣金
	 * 房费佣金+选配佣金	
	 * @return
	 */
	private Double getZyj() {
		return getFfyj2()+getXpyj();
	}

	public String getRzrqFormat() {
		return DateUtils.format(getRzrq());
	}
	public String getSqsjFormat() {
		return DateUtils.format(getSqsj());
	}
	public String getTfrqFormat() {
		return DateUtils.format(getTfrq());
	}
	
//入住日期范围
	@DateTimeFormat(iso=ISO.DATE) 
	private Date rzrqFrom;
	@DateTimeFormat(iso=ISO.DATE) 
	private Date rzrqTo;
//	退房日期范围
	@DateTimeFormat(iso=ISO.DATE) 
	private Date tfrqFrom;
	@DateTimeFormat(iso=ISO.DATE) 
	private Date tfrqTo;

	public Date getRzrqFrom() {
		return rzrqFrom;
	}

	public void setRzrqFrom(Date rzrqFrom) {
		this.rzrqFrom = rzrqFrom;
	}

	public Date getRzrqTo() {
		return rzrqTo;
	}

	public void setRzrqTo(Date rzrqTo) {
		this.rzrqTo = rzrqTo;
	}

	public Date getTfrqFrom() {
		return tfrqFrom;
	}

	public void setTfrqFrom(Date tfrqFrom) {
		this.tfrqFrom = tfrqFrom;
	}

	public Date getTfrqTo() {
		return tfrqTo;
	}

	public void setTfrqTo(Date tfrqTo) {
		this.tfrqTo = tfrqTo;
	}
	
	//房间
	private HouseVO house;

	public HouseVO getHouse() {
		return house;
	}

	public void setHouse(HouseVO house) {
		this.house = house;
	}
	
	//来源，中文描述
	private String source;

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}
	
	
	
}