package com.homtrip.model;

import java.math.BigDecimal;

public class HotelSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.cont
     *
     * @mbggenerated
     */
    private Long cont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.ts
     *
     * @mbggenerated
     */
    private BigDecimal ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.hotelName
     *
     * @mbggenerated
     */
    private String hotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.xpze
     *
     * @mbggenerated
     */
    private Double xpze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.yhje
     *
     * @mbggenerated
     */
    private Double yhje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.xfje
     *
     * @mbggenerated
     */
    private Double xfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.ffyj
     *
     * @mbggenerated
     */
    private Double ffyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.xpyj
     *
     * @mbggenerated
     */
    private Double xpyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_sum.jdfx
     *
     * @mbggenerated
     */
    private Double jdfx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.cont
     *
     * @return the value of hotel_sum.cont
     *
     * @mbggenerated
     */
    public Long getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.cont
     *
     * @param cont the value for hotel_sum.cont
     *
     * @mbggenerated
     */
    public void setCont(Long cont) {
        this.cont = cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.ts
     *
     * @return the value of hotel_sum.ts
     *
     * @mbggenerated
     */
    public BigDecimal getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.ts
     *
     * @param ts the value for hotel_sum.ts
     *
     * @mbggenerated
     */
    public void setTs(BigDecimal ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.hotelName
     *
     * @return the value of hotel_sum.hotelName
     *
     * @mbggenerated
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.hotelName
     *
     * @param hotelname the value for hotel_sum.hotelName
     *
     * @mbggenerated
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.xpze
     *
     * @return the value of hotel_sum.xpze
     *
     * @mbggenerated
     */
    public Double getXpze() {
        return xpze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.xpze
     *
     * @param xpze the value for hotel_sum.xpze
     *
     * @mbggenerated
     */
    public void setXpze(Double xpze) {
        this.xpze = xpze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.yhje
     *
     * @return the value of hotel_sum.yhje
     *
     * @mbggenerated
     */
    public Double getYhje() {
        return yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.yhje
     *
     * @param yhje the value for hotel_sum.yhje
     *
     * @mbggenerated
     */
    public void setYhje(Double yhje) {
        this.yhje = yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.xfje
     *
     * @return the value of hotel_sum.xfje
     *
     * @mbggenerated
     */
    public Double getXfje() {
        return xfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.xfje
     *
     * @param xfje the value for hotel_sum.xfje
     *
     * @mbggenerated
     */
    public void setXfje(Double xfje) {
        this.xfje = xfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.ffyj
     *
     * @return the value of hotel_sum.ffyj
     *
     * @mbggenerated
     */
    public Double getFfyj() {
        return ffyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.ffyj
     *
     * @param ffyj the value for hotel_sum.ffyj
     *
     * @mbggenerated
     */
    public void setFfyj(Double ffyj) {
        this.ffyj = ffyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.xpyj
     *
     * @return the value of hotel_sum.xpyj
     *
     * @mbggenerated
     */
    public Double getXpyj() {
        return xpyj;
    }

    @Override
	public String toString() {
		return "HotelSummary [cont=" + cont + ", ts=" + ts + ", hotelname=" + hotelname + ", xpze=" + xpze + ", yhje="
				+ yhje + ", xfje=" + xfje + ", ffyj=" + ffyj + ", xpyj=" + xpyj + ", jdfx=" + jdfx + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.xpyj
     *
     * @param xpyj the value for hotel_sum.xpyj
     *
     * @mbggenerated
     */
    public void setXpyj(Double xpyj) {
        this.xpyj = xpyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_sum.jdfx
     *
     * @return the value of hotel_sum.jdfx
     *
     * @mbggenerated
     */
    public Double getJdfx() {
        return jdfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_sum.jdfx
     *
     * @param jdfx the value for hotel_sum.jdfx
     *
     * @mbggenerated
     */
    public void setJdfx(Double jdfx) {
        this.jdfx = jdfx;
    }
}