package com.homtrip.model;

import java.util.ArrayList;
import java.util.List;

public class HouseCleanGrpMenberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public HouseCleanGrpMenberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGrpidIsNull() {
            addCriterion("grpId is null");
            return (Criteria) this;
        }

        public Criteria andGrpidIsNotNull() {
            addCriterion("grpId is not null");
            return (Criteria) this;
        }

        public Criteria andGrpidEqualTo(String value) {
            addCriterion("grpId =", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidNotEqualTo(String value) {
            addCriterion("grpId <>", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidGreaterThan(String value) {
            addCriterion("grpId >", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidGreaterThanOrEqualTo(String value) {
            addCriterion("grpId >=", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidLessThan(String value) {
            addCriterion("grpId <", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidLessThanOrEqualTo(String value) {
            addCriterion("grpId <=", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidLike(String value) {
            addCriterion("grpId like", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidNotLike(String value) {
            addCriterion("grpId not like", value, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidIn(List<String> values) {
            addCriterion("grpId in", values, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidNotIn(List<String> values) {
            addCriterion("grpId not in", values, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidBetween(String value1, String value2) {
            addCriterion("grpId between", value1, value2, "grpid");
            return (Criteria) this;
        }

        public Criteria andGrpidNotBetween(String value1, String value2) {
            addCriterion("grpId not between", value1, value2, "grpid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andGrxsIsNull() {
            addCriterion("grxs is null");
            return (Criteria) this;
        }

        public Criteria andGrxsIsNotNull() {
            addCriterion("grxs is not null");
            return (Criteria) this;
        }

        public Criteria andGrxsEqualTo(Double value) {
            addCriterion("grxs =", value, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsNotEqualTo(Double value) {
            addCriterion("grxs <>", value, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsGreaterThan(Double value) {
            addCriterion("grxs >", value, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsGreaterThanOrEqualTo(Double value) {
            addCriterion("grxs >=", value, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsLessThan(Double value) {
            addCriterion("grxs <", value, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsLessThanOrEqualTo(Double value) {
            addCriterion("grxs <=", value, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsIn(List<Double> values) {
            addCriterion("grxs in", values, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsNotIn(List<Double> values) {
            addCriterion("grxs not in", values, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsBetween(Double value1, Double value2) {
            addCriterion("grxs between", value1, value2, "grxs");
            return (Criteria) this;
        }

        public Criteria andGrxsNotBetween(Double value1, Double value2) {
            addCriterion("grxs not between", value1, value2, "grxs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}