package com.homtrip.model;

import java.util.Date;

public class HouseVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.instanceGuid
     *
     * @mbggenerated
     */
    private Integer instanceguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.gzlzt
     *
     * @mbggenerated
     */
    private String gzlzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.lcjssj
     *
     * @mbggenerated
     */
    private Date lcjssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sqbm
     *
     * @mbggenerated
     */
    private String sqbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sqbmguid
     *
     * @mbggenerated
     */
    private String sqbmguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ywy
     *
     * @mbggenerated
     */
    private String ywy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ywyid
     *
     * @mbggenerated
     */
    private String ywyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sqr
     *
     * @mbggenerated
     */
    private String sqr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sqrguid
     *
     * @mbggenerated
     */
    private String sqrguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.qtGuid
     *
     * @mbggenerated
     */
    private String qtguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yzGuid
     *
     * @mbggenerated
     */
    private String yzguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sqsj
     *
     * @mbggenerated
     */
    private Date sqsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fjmc
     *
     * @mbggenerated
     */
    private String fjmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.flid
     *
     * @mbggenerated
     */
    private String flid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zbh
     *
     * @mbggenerated
     */
    private String zbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htms
     *
     * @mbggenerated
     */
    private String htms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fcbl
     *
     * @mbggenerated
     */
    private Double fcbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sf
     *
     * @mbggenerated
     */
    private String sf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.cs
     *
     * @mbggenerated
     */
    private String cs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.qu
     *
     * @mbggenerated
     */
    private String qu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.jd
     *
     * @mbggenerated
     */
    private String jd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.xqhy
     *
     * @mbggenerated
     */
    private String xqhy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fangxing
     *
     * @mbggenerated
     */
    private String fangxing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.dong
     *
     * @mbggenerated
     */
    private Integer dong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.louceng
     *
     * @mbggenerated
     */
    private Integer louceng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fjh
     *
     * @mbggenerated
     */
    private Integer fjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yb
     *
     * @mbggenerated
     */
    private String yb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.xxdz
     *
     * @mbggenerated
     */
    private String xxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fx
     *
     * @mbggenerated
     */
    private String fx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fwmj
     *
     * @mbggenerated
     */
    private Integer fwmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.flss
     *
     * @mbggenerated
     */
    private String flss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.pt
     *
     * @mbggenerated
     */
    private String pt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fw
     *
     * @mbggenerated
     */
    private String fw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.qt
     *
     * @mbggenerated
     */
    private String qt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.rlGuid
     *
     * @mbggenerated
     */
    private String rlguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ksrq
     *
     * @mbggenerated
     */
    private Date ksrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.jsrq
     *
     * @mbggenerated
     */
    private Date jsrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.djsts
     *
     * @mbggenerated
     */
    private Integer djsts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htbh
     *
     * @mbggenerated
     */
    private String htbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htmslx
     *
     * @mbggenerated
     */
    private String htmslx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htyz
     *
     * @mbggenerated
     */
    private Double htyz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htyz1
     *
     * @mbggenerated
     */
    private Double htyz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.czffcbl
     *
     * @mbggenerated
     */
    private Double czffcbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.czffcbl1
     *
     * @mbggenerated
     */
    private Double czffcbl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.chzffcbl
     *
     * @mbggenerated
     */
    private Double chzffcbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.chzffcbl1
     *
     * @mbggenerated
     */
    private Double chzffcbl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ysf
     *
     * @mbggenerated
     */
    private Double ysf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zqjg
     *
     * @mbggenerated
     */
    private Double zqjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zqzs
     *
     * @mbggenerated
     */
    private Integer zqzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zqhjje
     *
     * @mbggenerated
     */
    private Double zqhjje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ycb
     *
     * @mbggenerated
     */
    private Double ycb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ncb
     *
     * @mbggenerated
     */
    private Double ncb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ysy
     *
     * @mbggenerated
     */
    private Double ysy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zsy
     *
     * @mbggenerated
     */
    private Double zsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ywysj
     *
     * @mbggenerated
     */
    private String ywysj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.ywydh
     *
     * @mbggenerated
     */
    private String ywydh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fptg
     *
     * @mbggenerated
     */
    private String fptg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zk
     *
     * @mbggenerated
     */
    private Double zk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yl
     *
     * @mbggenerated
     */
    private Double yl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.hl
     *
     * @mbggenerated
     */
    private Double hl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zfy
     *
     * @mbggenerated
     */
    private Double zfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zl
     *
     * @mbggenerated
     */
    private Double zl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.wzts
     *
     * @mbggenerated
     */
    private Integer wzts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.qlsj
     *
     * @mbggenerated
     */
    private Date qlsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.jjxz
     *
     * @mbggenerated
     */
    private String jjxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yjks
     *
     * @mbggenerated
     */
    private Double yjks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yfrq
     *
     * @mbggenerated
     */
    private Date yfrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.jjzfy
     *
     * @mbggenerated
     */
    private Double jjzfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yj
     *
     * @mbggenerated
     */
    private Double yj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zj
     *
     * @mbggenerated
     */
    private Double zj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sfdz
     *
     * @mbggenerated
     */
    private String sfdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zfms
     *
     * @mbggenerated
     */
    private String zfms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.zffs
     *
     * @mbggenerated
     */
    private String zffs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fkzq
     *
     * @mbggenerated
     */
    private String fkzq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.wlczf
     *
     * @mbggenerated
     */
    private Double wlczf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.qtfy
     *
     * @mbggenerated
     */
    private Double qtfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yzcdzfy
     *
     * @mbggenerated
     */
    private Double yzcdzfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.rsxz
     *
     * @mbggenerated
     */
    private Integer rsxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fkrq
     *
     * @mbggenerated
     */
    private Integer fkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fkxs
     *
     * @mbggenerated
     */
    private Integer fkxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fkfz
     *
     * @mbggenerated
     */
    private Integer fkfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fwzt
     *
     * @mbggenerated
     */
    private String fwzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fxGuid
     *
     * @mbggenerated
     */
    private String fxguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.issale
     *
     * @mbggenerated
     */
    private String issale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.tfjzq
     *
     * @mbggenerated
     */
    private Date tfjzq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.tfjj
     *
     * @mbggenerated
     */
    private Double tfjj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.glffzf
     *
     * @mbggenerated
     */
    private String glffzf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.sdffzf
     *
     * @mbggenerated
     */
    private String sdffzf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.fwbh
     *
     * @mbggenerated
     */
    private String fwbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htfj_ext
     *
     * @mbggenerated
     */
    private String htfjExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yjdfj_ext
     *
     * @mbggenerated
     */
    private String yjdfjExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.gfht_ext
     *
     * @mbggenerated
     */
    private String gfhtExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htmsdjfj_ext
     *
     * @mbggenerated
     */
    private String htmsdjfjExt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.guid
     *
     * @return the value of house.guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.guid
     *
     * @param guid the value for house.guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.instanceGuid
     *
     * @return the value of house.instanceGuid
     *
     * @mbggenerated
     */
    public Integer getInstanceguid() {
        return instanceguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.instanceGuid
     *
     * @param instanceguid the value for house.instanceGuid
     *
     * @mbggenerated
     */
    public void setInstanceguid(Integer instanceguid) {
        this.instanceguid = instanceguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.gzlzt
     *
     * @return the value of house.gzlzt
     *
     * @mbggenerated
     */
    public String getGzlzt() {
        return gzlzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.gzlzt
     *
     * @param gzlzt the value for house.gzlzt
     *
     * @mbggenerated
     */
    public void setGzlzt(String gzlzt) {
        this.gzlzt = gzlzt == null ? null : gzlzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.lcjssj
     *
     * @return the value of house.lcjssj
     *
     * @mbggenerated
     */
    public Date getLcjssj() {
        return lcjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.lcjssj
     *
     * @param lcjssj the value for house.lcjssj
     *
     * @mbggenerated
     */
    public void setLcjssj(Date lcjssj) {
        this.lcjssj = lcjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sqbm
     *
     * @return the value of house.sqbm
     *
     * @mbggenerated
     */
    public String getSqbm() {
        return sqbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sqbm
     *
     * @param sqbm the value for house.sqbm
     *
     * @mbggenerated
     */
    public void setSqbm(String sqbm) {
        this.sqbm = sqbm == null ? null : sqbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sqbmguid
     *
     * @return the value of house.sqbmguid
     *
     * @mbggenerated
     */
    public String getSqbmguid() {
        return sqbmguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sqbmguid
     *
     * @param sqbmguid the value for house.sqbmguid
     *
     * @mbggenerated
     */
    public void setSqbmguid(String sqbmguid) {
        this.sqbmguid = sqbmguid == null ? null : sqbmguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ywy
     *
     * @return the value of house.ywy
     *
     * @mbggenerated
     */
    public String getYwy() {
        return ywy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ywy
     *
     * @param ywy the value for house.ywy
     *
     * @mbggenerated
     */
    public void setYwy(String ywy) {
        this.ywy = ywy == null ? null : ywy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ywyid
     *
     * @return the value of house.ywyid
     *
     * @mbggenerated
     */
    public String getYwyid() {
        return ywyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ywyid
     *
     * @param ywyid the value for house.ywyid
     *
     * @mbggenerated
     */
    public void setYwyid(String ywyid) {
        this.ywyid = ywyid == null ? null : ywyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sqr
     *
     * @return the value of house.sqr
     *
     * @mbggenerated
     */
    public String getSqr() {
        return sqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sqr
     *
     * @param sqr the value for house.sqr
     *
     * @mbggenerated
     */
    public void setSqr(String sqr) {
        this.sqr = sqr == null ? null : sqr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sqrguid
     *
     * @return the value of house.sqrguid
     *
     * @mbggenerated
     */
    public String getSqrguid() {
        return sqrguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sqrguid
     *
     * @param sqrguid the value for house.sqrguid
     *
     * @mbggenerated
     */
    public void setSqrguid(String sqrguid) {
        this.sqrguid = sqrguid == null ? null : sqrguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.qtGuid
     *
     * @return the value of house.qtGuid
     *
     * @mbggenerated
     */
    public String getQtguid() {
        return qtguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.qtGuid
     *
     * @param qtguid the value for house.qtGuid
     *
     * @mbggenerated
     */
    public void setQtguid(String qtguid) {
        this.qtguid = qtguid == null ? null : qtguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yzGuid
     *
     * @return the value of house.yzGuid
     *
     * @mbggenerated
     */
    public String getYzguid() {
        return yzguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yzGuid
     *
     * @param yzguid the value for house.yzGuid
     *
     * @mbggenerated
     */
    public void setYzguid(String yzguid) {
        this.yzguid = yzguid == null ? null : yzguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sqsj
     *
     * @return the value of house.sqsj
     *
     * @mbggenerated
     */
    public Date getSqsj() {
        return sqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sqsj
     *
     * @param sqsj the value for house.sqsj
     *
     * @mbggenerated
     */
    public void setSqsj(Date sqsj) {
        this.sqsj = sqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fjmc
     *
     * @return the value of house.fjmc
     *
     * @mbggenerated
     */
    public String getFjmc() {
        return fjmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fjmc
     *
     * @param fjmc the value for house.fjmc
     *
     * @mbggenerated
     */
    public void setFjmc(String fjmc) {
        this.fjmc = fjmc == null ? null : fjmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.flid
     *
     * @return the value of house.flid
     *
     * @mbggenerated
     */
    public String getFlid() {
        return flid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.flid
     *
     * @param flid the value for house.flid
     *
     * @mbggenerated
     */
    public void setFlid(String flid) {
        this.flid = flid == null ? null : flid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zbh
     *
     * @return the value of house.zbh
     *
     * @mbggenerated
     */
    public String getZbh() {
        return zbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zbh
     *
     * @param zbh the value for house.zbh
     *
     * @mbggenerated
     */
    public void setZbh(String zbh) {
        this.zbh = zbh == null ? null : zbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htms
     *
     * @return the value of house.htms
     *
     * @mbggenerated
     */
    public String getHtms() {
        return htms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htms
     *
     * @param htms the value for house.htms
     *
     * @mbggenerated
     */
    public void setHtms(String htms) {
        this.htms = htms == null ? null : htms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fcbl
     *
     * @return the value of house.fcbl
     *
     * @mbggenerated
     */
    public Double getFcbl() {
        return fcbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fcbl
     *
     * @param fcbl the value for house.fcbl
     *
     * @mbggenerated
     */
    public void setFcbl(Double fcbl) {
        this.fcbl = fcbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sf
     *
     * @return the value of house.sf
     *
     * @mbggenerated
     */
    public String getSf() {
        return sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sf
     *
     * @param sf the value for house.sf
     *
     * @mbggenerated
     */
    public void setSf(String sf) {
        this.sf = sf == null ? null : sf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.cs
     *
     * @return the value of house.cs
     *
     * @mbggenerated
     */
    public String getCs() {
        return cs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.cs
     *
     * @param cs the value for house.cs
     *
     * @mbggenerated
     */
    public void setCs(String cs) {
        this.cs = cs == null ? null : cs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.qu
     *
     * @return the value of house.qu
     *
     * @mbggenerated
     */
    public String getQu() {
        return qu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.qu
     *
     * @param qu the value for house.qu
     *
     * @mbggenerated
     */
    public void setQu(String qu) {
        this.qu = qu == null ? null : qu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.jd
     *
     * @return the value of house.jd
     *
     * @mbggenerated
     */
    public String getJd() {
        return jd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.jd
     *
     * @param jd the value for house.jd
     *
     * @mbggenerated
     */
    public void setJd(String jd) {
        this.jd = jd == null ? null : jd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.xqhy
     *
     * @return the value of house.xqhy
     *
     * @mbggenerated
     */
    public String getXqhy() {
        return xqhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.xqhy
     *
     * @param xqhy the value for house.xqhy
     *
     * @mbggenerated
     */
    public void setXqhy(String xqhy) {
        this.xqhy = xqhy == null ? null : xqhy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fangxing
     *
     * @return the value of house.fangxing
     *
     * @mbggenerated
     */
    public String getFangxing() {
        return fangxing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fangxing
     *
     * @param fangxing the value for house.fangxing
     *
     * @mbggenerated
     */
    public void setFangxing(String fangxing) {
        this.fangxing = fangxing == null ? null : fangxing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.dong
     *
     * @return the value of house.dong
     *
     * @mbggenerated
     */
    public Integer getDong() {
        return dong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.dong
     *
     * @param dong the value for house.dong
     *
     * @mbggenerated
     */
    public void setDong(Integer dong) {
        this.dong = dong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.louceng
     *
     * @return the value of house.louceng
     *
     * @mbggenerated
     */
    public Integer getLouceng() {
        return louceng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.louceng
     *
     * @param louceng the value for house.louceng
     *
     * @mbggenerated
     */
    public void setLouceng(Integer louceng) {
        this.louceng = louceng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fjh
     *
     * @return the value of house.fjh
     *
     * @mbggenerated
     */
    public Integer getFjh() {
        return fjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fjh
     *
     * @param fjh the value for house.fjh
     *
     * @mbggenerated
     */
    public void setFjh(Integer fjh) {
        this.fjh = fjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yb
     *
     * @return the value of house.yb
     *
     * @mbggenerated
     */
    public String getYb() {
        return yb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yb
     *
     * @param yb the value for house.yb
     *
     * @mbggenerated
     */
    public void setYb(String yb) {
        this.yb = yb == null ? null : yb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.xxdz
     *
     * @return the value of house.xxdz
     *
     * @mbggenerated
     */
    public String getXxdz() {
        return xxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.xxdz
     *
     * @param xxdz the value for house.xxdz
     *
     * @mbggenerated
     */
    public void setXxdz(String xxdz) {
        this.xxdz = xxdz == null ? null : xxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fx
     *
     * @return the value of house.fx
     *
     * @mbggenerated
     */
    public String getFx() {
        return fx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fx
     *
     * @param fx the value for house.fx
     *
     * @mbggenerated
     */
    public void setFx(String fx) {
        this.fx = fx == null ? null : fx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fwmj
     *
     * @return the value of house.fwmj
     *
     * @mbggenerated
     */
    public Integer getFwmj() {
        return fwmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fwmj
     *
     * @param fwmj the value for house.fwmj
     *
     * @mbggenerated
     */
    public void setFwmj(Integer fwmj) {
        this.fwmj = fwmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.flss
     *
     * @return the value of house.flss
     *
     * @mbggenerated
     */
    public String getFlss() {
        return flss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.flss
     *
     * @param flss the value for house.flss
     *
     * @mbggenerated
     */
    public void setFlss(String flss) {
        this.flss = flss == null ? null : flss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.pt
     *
     * @return the value of house.pt
     *
     * @mbggenerated
     */
    public String getPt() {
        return pt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.pt
     *
     * @param pt the value for house.pt
     *
     * @mbggenerated
     */
    public void setPt(String pt) {
        this.pt = pt == null ? null : pt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fw
     *
     * @return the value of house.fw
     *
     * @mbggenerated
     */
    public String getFw() {
        return fw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fw
     *
     * @param fw the value for house.fw
     *
     * @mbggenerated
     */
    public void setFw(String fw) {
        this.fw = fw == null ? null : fw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.qt
     *
     * @return the value of house.qt
     *
     * @mbggenerated
     */
    public String getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.qt
     *
     * @param qt the value for house.qt
     *
     * @mbggenerated
     */
    public void setQt(String qt) {
        this.qt = qt == null ? null : qt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.rlGuid
     *
     * @return the value of house.rlGuid
     *
     * @mbggenerated
     */
    public String getRlguid() {
        return rlguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.rlGuid
     *
     * @param rlguid the value for house.rlGuid
     *
     * @mbggenerated
     */
    public void setRlguid(String rlguid) {
        this.rlguid = rlguid == null ? null : rlguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ksrq
     *
     * @return the value of house.ksrq
     *
     * @mbggenerated
     */
    public Date getKsrq() {
        return ksrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ksrq
     *
     * @param ksrq the value for house.ksrq
     *
     * @mbggenerated
     */
    public void setKsrq(Date ksrq) {
        this.ksrq = ksrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.jsrq
     *
     * @return the value of house.jsrq
     *
     * @mbggenerated
     */
    public Date getJsrq() {
        return jsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.jsrq
     *
     * @param jsrq the value for house.jsrq
     *
     * @mbggenerated
     */
    public void setJsrq(Date jsrq) {
        this.jsrq = jsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.djsts
     *
     * @return the value of house.djsts
     *
     * @mbggenerated
     */
    public Integer getDjsts() {
        return djsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.djsts
     *
     * @param djsts the value for house.djsts
     *
     * @mbggenerated
     */
    public void setDjsts(Integer djsts) {
        this.djsts = djsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htbh
     *
     * @return the value of house.htbh
     *
     * @mbggenerated
     */
    public String getHtbh() {
        return htbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htbh
     *
     * @param htbh the value for house.htbh
     *
     * @mbggenerated
     */
    public void setHtbh(String htbh) {
        this.htbh = htbh == null ? null : htbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htmslx
     *
     * @return the value of house.htmslx
     *
     * @mbggenerated
     */
    public String getHtmslx() {
        return htmslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htmslx
     *
     * @param htmslx the value for house.htmslx
     *
     * @mbggenerated
     */
    public void setHtmslx(String htmslx) {
        this.htmslx = htmslx == null ? null : htmslx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htyz
     *
     * @return the value of house.htyz
     *
     * @mbggenerated
     */
    public Double getHtyz() {
        return htyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htyz
     *
     * @param htyz the value for house.htyz
     *
     * @mbggenerated
     */
    public void setHtyz(Double htyz) {
        this.htyz = htyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htyz1
     *
     * @return the value of house.htyz1
     *
     * @mbggenerated
     */
    public Double getHtyz1() {
        return htyz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htyz1
     *
     * @param htyz1 the value for house.htyz1
     *
     * @mbggenerated
     */
    public void setHtyz1(Double htyz1) {
        this.htyz1 = htyz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.czffcbl
     *
     * @return the value of house.czffcbl
     *
     * @mbggenerated
     */
    public Double getCzffcbl() {
        return czffcbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.czffcbl
     *
     * @param czffcbl the value for house.czffcbl
     *
     * @mbggenerated
     */
    public void setCzffcbl(Double czffcbl) {
        this.czffcbl = czffcbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.czffcbl1
     *
     * @return the value of house.czffcbl1
     *
     * @mbggenerated
     */
    public Double getCzffcbl1() {
        return czffcbl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.czffcbl1
     *
     * @param czffcbl1 the value for house.czffcbl1
     *
     * @mbggenerated
     */
    public void setCzffcbl1(Double czffcbl1) {
        this.czffcbl1 = czffcbl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.chzffcbl
     *
     * @return the value of house.chzffcbl
     *
     * @mbggenerated
     */
    public Double getChzffcbl() {
        return chzffcbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.chzffcbl
     *
     * @param chzffcbl the value for house.chzffcbl
     *
     * @mbggenerated
     */
    public void setChzffcbl(Double chzffcbl) {
        this.chzffcbl = chzffcbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.chzffcbl1
     *
     * @return the value of house.chzffcbl1
     *
     * @mbggenerated
     */
    public Double getChzffcbl1() {
        return chzffcbl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.chzffcbl1
     *
     * @param chzffcbl1 the value for house.chzffcbl1
     *
     * @mbggenerated
     */
    public void setChzffcbl1(Double chzffcbl1) {
        this.chzffcbl1 = chzffcbl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ysf
     *
     * @return the value of house.ysf
     *
     * @mbggenerated
     */
    public Double getYsf() {
        return ysf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ysf
     *
     * @param ysf the value for house.ysf
     *
     * @mbggenerated
     */
    public void setYsf(Double ysf) {
        this.ysf = ysf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zqjg
     *
     * @return the value of house.zqjg
     *
     * @mbggenerated
     */
    public Double getZqjg() {
        return zqjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zqjg
     *
     * @param zqjg the value for house.zqjg
     *
     * @mbggenerated
     */
    public void setZqjg(Double zqjg) {
        this.zqjg = zqjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zqzs
     *
     * @return the value of house.zqzs
     *
     * @mbggenerated
     */
    public Integer getZqzs() {
        return zqzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zqzs
     *
     * @param zqzs the value for house.zqzs
     *
     * @mbggenerated
     */
    public void setZqzs(Integer zqzs) {
        this.zqzs = zqzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zqhjje
     *
     * @return the value of house.zqhjje
     *
     * @mbggenerated
     */
    public Double getZqhjje() {
        return zqhjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zqhjje
     *
     * @param zqhjje the value for house.zqhjje
     *
     * @mbggenerated
     */
    public void setZqhjje(Double zqhjje) {
        this.zqhjje = zqhjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ycb
     *
     * @return the value of house.ycb
     *
     * @mbggenerated
     */
    public Double getYcb() {
        return ycb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ycb
     *
     * @param ycb the value for house.ycb
     *
     * @mbggenerated
     */
    public void setYcb(Double ycb) {
        this.ycb = ycb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ncb
     *
     * @return the value of house.ncb
     *
     * @mbggenerated
     */
    public Double getNcb() {
        return ncb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ncb
     *
     * @param ncb the value for house.ncb
     *
     * @mbggenerated
     */
    public void setNcb(Double ncb) {
        this.ncb = ncb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ysy
     *
     * @return the value of house.ysy
     *
     * @mbggenerated
     */
    public Double getYsy() {
        return ysy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ysy
     *
     * @param ysy the value for house.ysy
     *
     * @mbggenerated
     */
    public void setYsy(Double ysy) {
        this.ysy = ysy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zsy
     *
     * @return the value of house.zsy
     *
     * @mbggenerated
     */
    public Double getZsy() {
        return zsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zsy
     *
     * @param zsy the value for house.zsy
     *
     * @mbggenerated
     */
    public void setZsy(Double zsy) {
        this.zsy = zsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ywysj
     *
     * @return the value of house.ywysj
     *
     * @mbggenerated
     */
    public String getYwysj() {
        return ywysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ywysj
     *
     * @param ywysj the value for house.ywysj
     *
     * @mbggenerated
     */
    public void setYwysj(String ywysj) {
        this.ywysj = ywysj == null ? null : ywysj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.ywydh
     *
     * @return the value of house.ywydh
     *
     * @mbggenerated
     */
    public String getYwydh() {
        return ywydh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.ywydh
     *
     * @param ywydh the value for house.ywydh
     *
     * @mbggenerated
     */
    public void setYwydh(String ywydh) {
        this.ywydh = ywydh == null ? null : ywydh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fptg
     *
     * @return the value of house.fptg
     *
     * @mbggenerated
     */
    public String getFptg() {
        return fptg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fptg
     *
     * @param fptg the value for house.fptg
     *
     * @mbggenerated
     */
    public void setFptg(String fptg) {
        this.fptg = fptg == null ? null : fptg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zk
     *
     * @return the value of house.zk
     *
     * @mbggenerated
     */
    public Double getZk() {
        return zk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zk
     *
     * @param zk the value for house.zk
     *
     * @mbggenerated
     */
    public void setZk(Double zk) {
        this.zk = zk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.price
     *
     * @return the value of house.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.price
     *
     * @param price the value for house.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yl
     *
     * @return the value of house.yl
     *
     * @mbggenerated
     */
    public Double getYl() {
        return yl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yl
     *
     * @param yl the value for house.yl
     *
     * @mbggenerated
     */
    public void setYl(Double yl) {
        this.yl = yl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.hl
     *
     * @return the value of house.hl
     *
     * @mbggenerated
     */
    public Double getHl() {
        return hl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.hl
     *
     * @param hl the value for house.hl
     *
     * @mbggenerated
     */
    public void setHl(Double hl) {
        this.hl = hl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zfy
     *
     * @return the value of house.zfy
     *
     * @mbggenerated
     */
    public Double getZfy() {
        return zfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zfy
     *
     * @param zfy the value for house.zfy
     *
     * @mbggenerated
     */
    public void setZfy(Double zfy) {
        this.zfy = zfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zl
     *
     * @return the value of house.zl
     *
     * @mbggenerated
     */
    public Double getZl() {
        return zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zl
     *
     * @param zl the value for house.zl
     *
     * @mbggenerated
     */
    public void setZl(Double zl) {
        this.zl = zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.wzts
     *
     * @return the value of house.wzts
     *
     * @mbggenerated
     */
    public Integer getWzts() {
        return wzts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.wzts
     *
     * @param wzts the value for house.wzts
     *
     * @mbggenerated
     */
    public void setWzts(Integer wzts) {
        this.wzts = wzts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.qlsj
     *
     * @return the value of house.qlsj
     *
     * @mbggenerated
     */
    public Date getQlsj() {
        return qlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.qlsj
     *
     * @param qlsj the value for house.qlsj
     *
     * @mbggenerated
     */
    public void setQlsj(Date qlsj) {
        this.qlsj = qlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.jjxz
     *
     * @return the value of house.jjxz
     *
     * @mbggenerated
     */
    public String getJjxz() {
        return jjxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.jjxz
     *
     * @param jjxz the value for house.jjxz
     *
     * @mbggenerated
     */
    public void setJjxz(String jjxz) {
        this.jjxz = jjxz == null ? null : jjxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yjks
     *
     * @return the value of house.yjks
     *
     * @mbggenerated
     */
    public Double getYjks() {
        return yjks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yjks
     *
     * @param yjks the value for house.yjks
     *
     * @mbggenerated
     */
    public void setYjks(Double yjks) {
        this.yjks = yjks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yfrq
     *
     * @return the value of house.yfrq
     *
     * @mbggenerated
     */
    public Date getYfrq() {
        return yfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yfrq
     *
     * @param yfrq the value for house.yfrq
     *
     * @mbggenerated
     */
    public void setYfrq(Date yfrq) {
        this.yfrq = yfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.jjzfy
     *
     * @return the value of house.jjzfy
     *
     * @mbggenerated
     */
    public Double getJjzfy() {
        return jjzfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.jjzfy
     *
     * @param jjzfy the value for house.jjzfy
     *
     * @mbggenerated
     */
    public void setJjzfy(Double jjzfy) {
        this.jjzfy = jjzfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yj
     *
     * @return the value of house.yj
     *
     * @mbggenerated
     */
    public Double getYj() {
        return yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yj
     *
     * @param yj the value for house.yj
     *
     * @mbggenerated
     */
    public void setYj(Double yj) {
        this.yj = yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zj
     *
     * @return the value of house.zj
     *
     * @mbggenerated
     */
    public Double getZj() {
        return zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zj
     *
     * @param zj the value for house.zj
     *
     * @mbggenerated
     */
    public void setZj(Double zj) {
        this.zj = zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sfdz
     *
     * @return the value of house.sfdz
     *
     * @mbggenerated
     */
    public String getSfdz() {
        return sfdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sfdz
     *
     * @param sfdz the value for house.sfdz
     *
     * @mbggenerated
     */
    public void setSfdz(String sfdz) {
        this.sfdz = sfdz == null ? null : sfdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zfms
     *
     * @return the value of house.zfms
     *
     * @mbggenerated
     */
    public String getZfms() {
        return zfms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zfms
     *
     * @param zfms the value for house.zfms
     *
     * @mbggenerated
     */
    public void setZfms(String zfms) {
        this.zfms = zfms == null ? null : zfms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.zffs
     *
     * @return the value of house.zffs
     *
     * @mbggenerated
     */
    public String getZffs() {
        return zffs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.zffs
     *
     * @param zffs the value for house.zffs
     *
     * @mbggenerated
     */
    public void setZffs(String zffs) {
        this.zffs = zffs == null ? null : zffs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fkzq
     *
     * @return the value of house.fkzq
     *
     * @mbggenerated
     */
    public String getFkzq() {
        return fkzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fkzq
     *
     * @param fkzq the value for house.fkzq
     *
     * @mbggenerated
     */
    public void setFkzq(String fkzq) {
        this.fkzq = fkzq == null ? null : fkzq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.wlczf
     *
     * @return the value of house.wlczf
     *
     * @mbggenerated
     */
    public Double getWlczf() {
        return wlczf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.wlczf
     *
     * @param wlczf the value for house.wlczf
     *
     * @mbggenerated
     */
    public void setWlczf(Double wlczf) {
        this.wlczf = wlczf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.qtfy
     *
     * @return the value of house.qtfy
     *
     * @mbggenerated
     */
    public Double getQtfy() {
        return qtfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.qtfy
     *
     * @param qtfy the value for house.qtfy
     *
     * @mbggenerated
     */
    public void setQtfy(Double qtfy) {
        this.qtfy = qtfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yzcdzfy
     *
     * @return the value of house.yzcdzfy
     *
     * @mbggenerated
     */
    public Double getYzcdzfy() {
        return yzcdzfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yzcdzfy
     *
     * @param yzcdzfy the value for house.yzcdzfy
     *
     * @mbggenerated
     */
    public void setYzcdzfy(Double yzcdzfy) {
        this.yzcdzfy = yzcdzfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.rsxz
     *
     * @return the value of house.rsxz
     *
     * @mbggenerated
     */
    public Integer getRsxz() {
        return rsxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.rsxz
     *
     * @param rsxz the value for house.rsxz
     *
     * @mbggenerated
     */
    public void setRsxz(Integer rsxz) {
        this.rsxz = rsxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fkrq
     *
     * @return the value of house.fkrq
     *
     * @mbggenerated
     */
    public Integer getFkrq() {
        return fkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fkrq
     *
     * @param fkrq the value for house.fkrq
     *
     * @mbggenerated
     */
    public void setFkrq(Integer fkrq) {
        this.fkrq = fkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fkxs
     *
     * @return the value of house.fkxs
     *
     * @mbggenerated
     */
    public Integer getFkxs() {
        return fkxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fkxs
     *
     * @param fkxs the value for house.fkxs
     *
     * @mbggenerated
     */
    public void setFkxs(Integer fkxs) {
        this.fkxs = fkxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fkfz
     *
     * @return the value of house.fkfz
     *
     * @mbggenerated
     */
    public Integer getFkfz() {
        return fkfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fkfz
     *
     * @param fkfz the value for house.fkfz
     *
     * @mbggenerated
     */
    public void setFkfz(Integer fkfz) {
        this.fkfz = fkfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fwzt
     *
     * @return the value of house.fwzt
     *
     * @mbggenerated
     */
    public String getFwzt() {
        return fwzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fwzt
     *
     * @param fwzt the value for house.fwzt
     *
     * @mbggenerated
     */
    public void setFwzt(String fwzt) {
        this.fwzt = fwzt == null ? null : fwzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fxGuid
     *
     * @return the value of house.fxGuid
     *
     * @mbggenerated
     */
    public String getFxguid() {
        return fxguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fxGuid
     *
     * @param fxguid the value for house.fxGuid
     *
     * @mbggenerated
     */
    public void setFxguid(String fxguid) {
        this.fxguid = fxguid == null ? null : fxguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.issale
     *
     * @return the value of house.issale
     *
     * @mbggenerated
     */
    public String getIssale() {
        return issale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.issale
     *
     * @param issale the value for house.issale
     *
     * @mbggenerated
     */
    public void setIssale(String issale) {
        this.issale = issale == null ? null : issale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.bz
     *
     * @return the value of house.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.bz
     *
     * @param bz the value for house.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.tfjzq
     *
     * @return the value of house.tfjzq
     *
     * @mbggenerated
     */
    public Date getTfjzq() {
        return tfjzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.tfjzq
     *
     * @param tfjzq the value for house.tfjzq
     *
     * @mbggenerated
     */
    public void setTfjzq(Date tfjzq) {
        this.tfjzq = tfjzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.tfjj
     *
     * @return the value of house.tfjj
     *
     * @mbggenerated
     */
    public Double getTfjj() {
        return tfjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.tfjj
     *
     * @param tfjj the value for house.tfjj
     *
     * @mbggenerated
     */
    public void setTfjj(Double tfjj) {
        this.tfjj = tfjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.glffzf
     *
     * @return the value of house.glffzf
     *
     * @mbggenerated
     */
    public String getGlffzf() {
        return glffzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.glffzf
     *
     * @param glffzf the value for house.glffzf
     *
     * @mbggenerated
     */
    public void setGlffzf(String glffzf) {
        this.glffzf = glffzf == null ? null : glffzf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.sdffzf
     *
     * @return the value of house.sdffzf
     *
     * @mbggenerated
     */
    public String getSdffzf() {
        return sdffzf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.sdffzf
     *
     * @param sdffzf the value for house.sdffzf
     *
     * @mbggenerated
     */
    public void setSdffzf(String sdffzf) {
        this.sdffzf = sdffzf == null ? null : sdffzf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.fwbh
     *
     * @return the value of house.fwbh
     *
     * @mbggenerated
     */
    public String getFwbh() {
        return fwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.fwbh
     *
     * @param fwbh the value for house.fwbh
     *
     * @mbggenerated
     */
    public void setFwbh(String fwbh) {
        this.fwbh = fwbh == null ? null : fwbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htfj_ext
     *
     * @return the value of house.htfj_ext
     *
     * @mbggenerated
     */
    public String getHtfjExt() {
        return htfjExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htfj_ext
     *
     * @param htfjExt the value for house.htfj_ext
     *
     * @mbggenerated
     */
    public void setHtfjExt(String htfjExt) {
        this.htfjExt = htfjExt == null ? null : htfjExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yjdfj_ext
     *
     * @return the value of house.yjdfj_ext
     *
     * @mbggenerated
     */
    public String getYjdfjExt() {
        return yjdfjExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yjdfj_ext
     *
     * @param yjdfjExt the value for house.yjdfj_ext
     *
     * @mbggenerated
     */
    public void setYjdfjExt(String yjdfjExt) {
        this.yjdfjExt = yjdfjExt == null ? null : yjdfjExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.gfht_ext
     *
     * @return the value of house.gfht_ext
     *
     * @mbggenerated
     */
    public String getGfhtExt() {
        return gfhtExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.gfht_ext
     *
     * @param gfhtExt the value for house.gfht_ext
     *
     * @mbggenerated
     */
    public void setGfhtExt(String gfhtExt) {
        this.gfhtExt = gfhtExt == null ? null : gfhtExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htmsdjfj_ext
     *
     * @return the value of house.htmsdjfj_ext
     *
     * @mbggenerated
     */
    public String getHtmsdjfjExt() {
        return htmsdjfjExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htmsdjfj_ext
     *
     * @param htmsdjfjExt the value for house.htmsdjfj_ext
     *
     * @mbggenerated
     */
    public void setHtmsdjfjExt(String htmsdjfjExt) {
        this.htmsdjfjExt = htmsdjfjExt == null ? null : htmsdjfjExt.trim();
    }
    
    private String hotelName;

	public String getHotelName() {
		return hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}
	
	private HouseCleanInfo cleanInfo;
	
	private HouseCheckInfo checkInfo;
	
	private HouseOwner owner;

	public HouseCleanInfo getCleanInfo() {
		return cleanInfo;
	}

	public void setCleanInfo(HouseCleanInfo cleanInfo) {
		this.cleanInfo = cleanInfo;
	}

	public HouseCheckInfo getCheckInfo() {
		return checkInfo;
	}

	public void setCheckInfo(HouseCheckInfo checkInfo) {
		this.checkInfo = checkInfo;
	}

	public HouseOwner getOwner() {
		return owner;
	}

	public void setOwner(HouseOwner owner) {
		this.owner = owner;
	}
	
	
    
    
}