package com.homtrip.model;

public class HouseVOWithBLOBs extends HouseVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htfj
     *
     * @mbggenerated
     */
    private byte[] htfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.yjdfj
     *
     * @mbggenerated
     */
    private byte[] yjdfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.gfht
     *
     * @mbggenerated
     */
    private byte[] gfht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.htmsdjfj
     *
     * @mbggenerated
     */
    private byte[] htmsdjfj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htfj
     *
     * @return the value of house.htfj
     *
     * @mbggenerated
     */
    public byte[] getHtfj() {
        return htfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htfj
     *
     * @param htfj the value for house.htfj
     *
     * @mbggenerated
     */
    public void setHtfj(byte[] htfj) {
        this.htfj = htfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.yjdfj
     *
     * @return the value of house.yjdfj
     *
     * @mbggenerated
     */
    public byte[] getYjdfj() {
        return yjdfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.yjdfj
     *
     * @param yjdfj the value for house.yjdfj
     *
     * @mbggenerated
     */
    public void setYjdfj(byte[] yjdfj) {
        this.yjdfj = yjdfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.gfht
     *
     * @return the value of house.gfht
     *
     * @mbggenerated
     */
    public byte[] getGfht() {
        return gfht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.gfht
     *
     * @param gfht the value for house.gfht
     *
     * @mbggenerated
     */
    public void setGfht(byte[] gfht) {
        this.gfht = gfht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.htmsdjfj
     *
     * @return the value of house.htmsdjfj
     *
     * @mbggenerated
     */
    public byte[] getHtmsdjfj() {
        return htmsdjfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.htmsdjfj
     *
     * @param htmsdjfj the value for house.htmsdjfj
     *
     * @mbggenerated
     */
    public void setHtmsdjfj(byte[] htmsdjfj) {
        this.htmsdjfj = htmsdjfj;
    }
}