package com.homtrip.model;

import java.util.Date;
import java.util.List;

public class HouseCleanGrp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.grp
     *
     * @mbggenerated
     */
    private String grp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.bc
     *
     * @mbggenerated
     */
    private String bc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.sbsj
     *
     * @mbggenerated
     */
    private Date sbsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.xbsj
     *
     * @mbggenerated
     */
    private Date xbsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.pb
     *
     * @mbggenerated
     */
    private String pb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.fjzs
     *
     * @mbggenerated
     */
    private Double fjzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.zrs
     *
     * @mbggenerated
     */
    private Integer zrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.zxs
     *
     * @mbggenerated
     */
    private Date zxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp.qjsj
     *
     * @mbggenerated
     */
    private Date qjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.id
     *
     * @return the value of house_clean_grp.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.id
     *
     * @param id the value for house_clean_grp.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.grp
     *
     * @return the value of house_clean_grp.grp
     *
     * @mbggenerated
     */
    public String getGrp() {
        return grp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.grp
     *
     * @param grp the value for house_clean_grp.grp
     *
     * @mbggenerated
     */
    public void setGrp(String grp) {
        this.grp = grp == null ? null : grp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.bc
     *
     * @return the value of house_clean_grp.bc
     *
     * @mbggenerated
     */
    public String getBc() {
        return bc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.bc
     *
     * @param bc the value for house_clean_grp.bc
     *
     * @mbggenerated
     */
    public void setBc(String bc) {
        this.bc = bc == null ? null : bc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.sbsj
     *
     * @return the value of house_clean_grp.sbsj
     *
     * @mbggenerated
     */
    public Date getSbsj() {
        return sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.sbsj
     *
     * @param sbsj the value for house_clean_grp.sbsj
     *
     * @mbggenerated
     */
    public void setSbsj(Date sbsj) {
        this.sbsj = sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.xbsj
     *
     * @return the value of house_clean_grp.xbsj
     *
     * @mbggenerated
     */
    public Date getXbsj() {
        return xbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.xbsj
     *
     * @param xbsj the value for house_clean_grp.xbsj
     *
     * @mbggenerated
     */
    public void setXbsj(Date xbsj) {
        this.xbsj = xbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.pb
     *
     * @return the value of house_clean_grp.pb
     *
     * @mbggenerated
     */
    public String getPb() {
        return pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.pb
     *
     * @param pb the value for house_clean_grp.pb
     *
     * @mbggenerated
     */
    public void setPb(String pb) {
        this.pb = pb == null ? null : pb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.fjzs
     *
     * @return the value of house_clean_grp.fjzs
     *
     * @mbggenerated
     */
    public Double getFjzs() {
        return fjzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.fjzs
     *
     * @param fjzs the value for house_clean_grp.fjzs
     *
     * @mbggenerated
     */
    public void setFjzs(Double fjzs) {
        this.fjzs = fjzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.zrs
     *
     * @return the value of house_clean_grp.zrs
     *
     * @mbggenerated
     */
    public Integer getZrs() {
        return zrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.zrs
     *
     * @param zrs the value for house_clean_grp.zrs
     *
     * @mbggenerated
     */
    public void setZrs(Integer zrs) {
        this.zrs = zrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.zxs
     *
     * @return the value of house_clean_grp.zxs
     *
     * @mbggenerated
     */
    public Date getZxs() {
        return zxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.zxs
     *
     * @param zxs the value for house_clean_grp.zxs
     *
     * @mbggenerated
     */
    public void setZxs(Date zxs) {
        this.zxs = zxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp.qjsj
     *
     * @return the value of house_clean_grp.qjsj
     *
     * @mbggenerated
     */
    public Date getQjsj() {
        return qjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp.qjsj
     *
     * @param qjsj the value for house_clean_grp.qjsj
     *
     * @mbggenerated
     */
    public void setQjsj(Date qjsj) {
        this.qjsj = qjsj;
    }
    
    private List<HouseCleanGrpMenber> menbers;

	public List<HouseCleanGrpMenber> getMenbers() {
		return menbers;
	}

	public void setMenbers(List<HouseCleanGrpMenber> menbers) {
		this.menbers = menbers;
	}
    
    
    
}