package com.homtrip.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HouseCleanGrpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public HouseCleanGrpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGrpIsNull() {
            addCriterion("grp is null");
            return (Criteria) this;
        }

        public Criteria andGrpIsNotNull() {
            addCriterion("grp is not null");
            return (Criteria) this;
        }

        public Criteria andGrpEqualTo(String value) {
            addCriterion("grp =", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpNotEqualTo(String value) {
            addCriterion("grp <>", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpGreaterThan(String value) {
            addCriterion("grp >", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpGreaterThanOrEqualTo(String value) {
            addCriterion("grp >=", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpLessThan(String value) {
            addCriterion("grp <", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpLessThanOrEqualTo(String value) {
            addCriterion("grp <=", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpLike(String value) {
            addCriterion("grp like", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpNotLike(String value) {
            addCriterion("grp not like", value, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpIn(List<String> values) {
            addCriterion("grp in", values, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpNotIn(List<String> values) {
            addCriterion("grp not in", values, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpBetween(String value1, String value2) {
            addCriterion("grp between", value1, value2, "grp");
            return (Criteria) this;
        }

        public Criteria andGrpNotBetween(String value1, String value2) {
            addCriterion("grp not between", value1, value2, "grp");
            return (Criteria) this;
        }

        public Criteria andBcIsNull() {
            addCriterion("bc is null");
            return (Criteria) this;
        }

        public Criteria andBcIsNotNull() {
            addCriterion("bc is not null");
            return (Criteria) this;
        }

        public Criteria andBcEqualTo(String value) {
            addCriterion("bc =", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcNotEqualTo(String value) {
            addCriterion("bc <>", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcGreaterThan(String value) {
            addCriterion("bc >", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcGreaterThanOrEqualTo(String value) {
            addCriterion("bc >=", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcLessThan(String value) {
            addCriterion("bc <", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcLessThanOrEqualTo(String value) {
            addCriterion("bc <=", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcLike(String value) {
            addCriterion("bc like", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcNotLike(String value) {
            addCriterion("bc not like", value, "bc");
            return (Criteria) this;
        }

        public Criteria andBcIn(List<String> values) {
            addCriterion("bc in", values, "bc");
            return (Criteria) this;
        }

        public Criteria andBcNotIn(List<String> values) {
            addCriterion("bc not in", values, "bc");
            return (Criteria) this;
        }

        public Criteria andBcBetween(String value1, String value2) {
            addCriterion("bc between", value1, value2, "bc");
            return (Criteria) this;
        }

        public Criteria andBcNotBetween(String value1, String value2) {
            addCriterion("bc not between", value1, value2, "bc");
            return (Criteria) this;
        }

        public Criteria andSbsjIsNull() {
            addCriterion("sbsj is null");
            return (Criteria) this;
        }

        public Criteria andSbsjIsNotNull() {
            addCriterion("sbsj is not null");
            return (Criteria) this;
        }

        public Criteria andSbsjEqualTo(Date value) {
            addCriterionForJDBCDate("sbsj =", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("sbsj <>", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjGreaterThan(Date value) {
            addCriterionForJDBCDate("sbsj >", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sbsj >=", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjLessThan(Date value) {
            addCriterionForJDBCDate("sbsj <", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sbsj <=", value, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjIn(List<Date> values) {
            addCriterionForJDBCDate("sbsj in", values, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("sbsj not in", values, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sbsj between", value1, value2, "sbsj");
            return (Criteria) this;
        }

        public Criteria andSbsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sbsj not between", value1, value2, "sbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjIsNull() {
            addCriterion("xbsj is null");
            return (Criteria) this;
        }

        public Criteria andXbsjIsNotNull() {
            addCriterion("xbsj is not null");
            return (Criteria) this;
        }

        public Criteria andXbsjEqualTo(Date value) {
            addCriterionForJDBCDate("xbsj =", value, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("xbsj <>", value, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjGreaterThan(Date value) {
            addCriterionForJDBCDate("xbsj >", value, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("xbsj >=", value, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjLessThan(Date value) {
            addCriterionForJDBCDate("xbsj <", value, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("xbsj <=", value, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjIn(List<Date> values) {
            addCriterionForJDBCDate("xbsj in", values, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("xbsj not in", values, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("xbsj between", value1, value2, "xbsj");
            return (Criteria) this;
        }

        public Criteria andXbsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("xbsj not between", value1, value2, "xbsj");
            return (Criteria) this;
        }

        public Criteria andPbIsNull() {
            addCriterion("pb is null");
            return (Criteria) this;
        }

        public Criteria andPbIsNotNull() {
            addCriterion("pb is not null");
            return (Criteria) this;
        }

        public Criteria andPbEqualTo(String value) {
            addCriterion("pb =", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotEqualTo(String value) {
            addCriterion("pb <>", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThan(String value) {
            addCriterion("pb >", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbGreaterThanOrEqualTo(String value) {
            addCriterion("pb >=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThan(String value) {
            addCriterion("pb <", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLessThanOrEqualTo(String value) {
            addCriterion("pb <=", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbLike(String value) {
            addCriterion("pb like", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotLike(String value) {
            addCriterion("pb not like", value, "pb");
            return (Criteria) this;
        }

        public Criteria andPbIn(List<String> values) {
            addCriterion("pb in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotIn(List<String> values) {
            addCriterion("pb not in", values, "pb");
            return (Criteria) this;
        }

        public Criteria andPbBetween(String value1, String value2) {
            addCriterion("pb between", value1, value2, "pb");
            return (Criteria) this;
        }

        public Criteria andPbNotBetween(String value1, String value2) {
            addCriterion("pb not between", value1, value2, "pb");
            return (Criteria) this;
        }

        public Criteria andFjzsIsNull() {
            addCriterion("fjzs is null");
            return (Criteria) this;
        }

        public Criteria andFjzsIsNotNull() {
            addCriterion("fjzs is not null");
            return (Criteria) this;
        }

        public Criteria andFjzsEqualTo(Double value) {
            addCriterion("fjzs =", value, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsNotEqualTo(Double value) {
            addCriterion("fjzs <>", value, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsGreaterThan(Double value) {
            addCriterion("fjzs >", value, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsGreaterThanOrEqualTo(Double value) {
            addCriterion("fjzs >=", value, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsLessThan(Double value) {
            addCriterion("fjzs <", value, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsLessThanOrEqualTo(Double value) {
            addCriterion("fjzs <=", value, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsIn(List<Double> values) {
            addCriterion("fjzs in", values, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsNotIn(List<Double> values) {
            addCriterion("fjzs not in", values, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsBetween(Double value1, Double value2) {
            addCriterion("fjzs between", value1, value2, "fjzs");
            return (Criteria) this;
        }

        public Criteria andFjzsNotBetween(Double value1, Double value2) {
            addCriterion("fjzs not between", value1, value2, "fjzs");
            return (Criteria) this;
        }

        public Criteria andZrsIsNull() {
            addCriterion("zrs is null");
            return (Criteria) this;
        }

        public Criteria andZrsIsNotNull() {
            addCriterion("zrs is not null");
            return (Criteria) this;
        }

        public Criteria andZrsEqualTo(Integer value) {
            addCriterion("zrs =", value, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsNotEqualTo(Integer value) {
            addCriterion("zrs <>", value, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsGreaterThan(Integer value) {
            addCriterion("zrs >", value, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsGreaterThanOrEqualTo(Integer value) {
            addCriterion("zrs >=", value, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsLessThan(Integer value) {
            addCriterion("zrs <", value, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsLessThanOrEqualTo(Integer value) {
            addCriterion("zrs <=", value, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsIn(List<Integer> values) {
            addCriterion("zrs in", values, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsNotIn(List<Integer> values) {
            addCriterion("zrs not in", values, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsBetween(Integer value1, Integer value2) {
            addCriterion("zrs between", value1, value2, "zrs");
            return (Criteria) this;
        }

        public Criteria andZrsNotBetween(Integer value1, Integer value2) {
            addCriterion("zrs not between", value1, value2, "zrs");
            return (Criteria) this;
        }

        public Criteria andZxsIsNull() {
            addCriterion("zxs is null");
            return (Criteria) this;
        }

        public Criteria andZxsIsNotNull() {
            addCriterion("zxs is not null");
            return (Criteria) this;
        }

        public Criteria andZxsEqualTo(Date value) {
            addCriterionForJDBCDate("zxs =", value, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsNotEqualTo(Date value) {
            addCriterionForJDBCDate("zxs <>", value, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsGreaterThan(Date value) {
            addCriterionForJDBCDate("zxs >", value, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zxs >=", value, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsLessThan(Date value) {
            addCriterionForJDBCDate("zxs <", value, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zxs <=", value, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsIn(List<Date> values) {
            addCriterionForJDBCDate("zxs in", values, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsNotIn(List<Date> values) {
            addCriterionForJDBCDate("zxs not in", values, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zxs between", value1, value2, "zxs");
            return (Criteria) this;
        }

        public Criteria andZxsNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zxs not between", value1, value2, "zxs");
            return (Criteria) this;
        }

        public Criteria andQjsjIsNull() {
            addCriterion("qjsj is null");
            return (Criteria) this;
        }

        public Criteria andQjsjIsNotNull() {
            addCriterion("qjsj is not null");
            return (Criteria) this;
        }

        public Criteria andQjsjEqualTo(Date value) {
            addCriterionForJDBCDate("qjsj =", value, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("qjsj <>", value, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjGreaterThan(Date value) {
            addCriterionForJDBCDate("qjsj >", value, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("qjsj >=", value, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjLessThan(Date value) {
            addCriterionForJDBCDate("qjsj <", value, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("qjsj <=", value, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjIn(List<Date> values) {
            addCriterionForJDBCDate("qjsj in", values, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("qjsj not in", values, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("qjsj between", value1, value2, "qjsj");
            return (Criteria) this;
        }

        public Criteria andQjsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("qjsj not between", value1, value2, "qjsj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_clean_grp
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house_clean_grp
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}