package com.homtrip.model;

public class HouseCleanGrpMenber {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp_menber.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp_menber.grpId
     *
     * @mbggenerated
     */
    private String grpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp_menber.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_clean_grp_menber.grxs
     *
     * @mbggenerated
     */
    private Double grxs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp_menber.id
     *
     * @return the value of house_clean_grp_menber.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp_menber.id
     *
     * @param id the value for house_clean_grp_menber.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp_menber.grpId
     *
     * @return the value of house_clean_grp_menber.grpId
     *
     * @mbggenerated
     */
    public String getGrpid() {
        return grpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp_menber.grpId
     *
     * @param grpid the value for house_clean_grp_menber.grpId
     *
     * @mbggenerated
     */
    public void setGrpid(String grpid) {
        this.grpid = grpid == null ? null : grpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp_menber.name
     *
     * @return the value of house_clean_grp_menber.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp_menber.name
     *
     * @param name the value for house_clean_grp_menber.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_clean_grp_menber.grxs
     *
     * @return the value of house_clean_grp_menber.grxs
     *
     * @mbggenerated
     */
    public Double getGrxs() {
        return grxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_clean_grp_menber.grxs
     *
     * @param grxs the value for house_clean_grp_menber.grxs
     *
     * @mbggenerated
     */
    public void setGrxs(Double grxs) {
        this.grxs = grxs;
    }
}