package com.homtrip.common.mapper;

import com.homtrip.common.model.CodeItem;
import com.homtrip.common.model.CodeItemExample;
import com.homtrip.common.model.CodeItemKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int countByExample(CodeItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int deleteByExample(CodeItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CodeItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int insert(CodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int insertSelective(CodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    List<CodeItem> selectByExample(CodeItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    CodeItem selectByPrimaryKey(CodeItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CodeItem record, @Param("example") CodeItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CodeItem record, @Param("example") CodeItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoncodeitem_sys
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeItem record);
}