package com.homtrip.common.model;

public class CodeItemKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoncodeitem_sys.Code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoncodeitem_sys.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoncodeitem_sys.Code
     *
     * @return the value of commoncodeitem_sys.Code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoncodeitem_sys.Code
     *
     * @param code the value for commoncodeitem_sys.Code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoncodeitem_sys.Id
     *
     * @return the value of commoncodeitem_sys.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoncodeitem_sys.Id
     *
     * @param id the value for commoncodeitem_sys.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}