package com.homtrip.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.homtrip.model.HotelOrderVO;
import com.homtrip.model.HotelOrderVOExample;
import com.homtrip.model.HotelSummary;

public interface HotelOrderVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int countByExample(HotelOrderVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int deleteByExample(HotelOrderVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int insert(HotelOrderVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int insertSelective(HotelOrderVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    List<HotelOrderVO> selectByExampleWithBLOBs(HotelOrderVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    List<HotelOrderVO> selectByExample(HotelOrderVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    HotelOrderVO selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HotelOrderVO record, @Param("example") HotelOrderVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") HotelOrderVO record, @Param("example") HotelOrderVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HotelOrderVO record, @Param("example") HotelOrderVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotelOrderVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(HotelOrderVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwddzb
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotelOrderVO record);

    List<Map<String, Object>> selectOrderCount(HotelOrderVOExample example);

	HotelSummary selectSummary(String hotelName);
}