package com.homtrip.mapper;

import com.homtrip.model.HouseCleanInfo;
import com.homtrip.model.HouseCleanInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseCleanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int countByExample(HouseCleanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int deleteByExample(HouseCleanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int insert(HouseCleanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int insertSelective(HouseCleanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    List<HouseCleanInfo> selectByExample(HouseCleanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    HouseCleanInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HouseCleanInfo record, @Param("example") HouseCleanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HouseCleanInfo record, @Param("example") HouseCleanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseCleanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseCleanInfo record);
}