package com.homtrip.mapper;

import com.homtrip.model.HouseCleanGrpMenber;
import com.homtrip.model.HouseCleanGrpMenberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseCleanGrpMenberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int countByExample(HouseCleanGrpMenberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int deleteByExample(HouseCleanGrpMenberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int insert(HouseCleanGrpMenber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int insertSelective(HouseCleanGrpMenber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    List<HouseCleanGrpMenber> selectByExample(HouseCleanGrpMenberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    HouseCleanGrpMenber selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HouseCleanGrpMenber record, @Param("example") HouseCleanGrpMenberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HouseCleanGrpMenber record, @Param("example") HouseCleanGrpMenberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseCleanGrpMenber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_clean_grp_menber
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseCleanGrpMenber record);
}