package com.homtrip.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.homtrip.model.HouseVO;
import com.homtrip.model.HouseVOExample;
import com.homtrip.model.HouseVOWithBLOBs;

public interface HouseVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int countByExample(HouseVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int deleteByExample(HouseVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int insert(HouseVOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int insertSelective(HouseVOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    List<HouseVOWithBLOBs> selectByExampleWithBLOBs(HouseVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    List<HouseVO> selectByExample(HouseVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    HouseVOWithBLOBs selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HouseVOWithBLOBs record, @Param("example") HouseVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") HouseVOWithBLOBs record, @Param("example") HouseVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HouseVO record, @Param("example") HouseVOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseVOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(HouseVOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseVO record);
}